import os
import random
import re
from datetime import datetime, timedelta
from urllib.parse import urlparse
from dotenv import load_dotenv
from flask import Flask, redirect, render_template, request, session, url_for
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from itsdangerous import BadSignature, SignatureExpired, URLSafeTimedSerializer
from openpyxl import load_workbook
from flask_sqlalchemy import SQLAlchemy
from flask_wtf.csrf import CSRFProtect
from sqlalchemy import inspect, or_, text
from sqlalchemy.exc import OperationalError
from werkzeug.exceptions import RequestEntityTooLarge
from werkzeug.middleware.proxy_fix import ProxyFix
from werkzeug.security import check_password_hash, generate_password_hash

load_dotenv()

TRUE_VALUES = {"1", "true", "yes", "on"}


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in TRUE_VALUES


def env_int(name, default):
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return int(value.strip())
    except (TypeError, ValueError):
        return default


def is_local_dev_environment():
    app_env = os.getenv("APP_ENV", "").strip().lower()
    flask_env = os.getenv("FLASK_ENV", "").strip().lower()
    return (
        env_bool("FLASK_DEBUG", False)
        or app_env in {"local", "development", "dev"}
        or flask_env in {"local", "development", "dev"}
    )

##Code was scaffolded by me, then heavily expanded and polished with the help of ChatGPT Codex. The overall architecture and ideas were done by me.
##HTML was generated by ChatGPT with some manual tweaks.
app = Flask(__name__)
if env_bool("TRUST_PROXY_HEADERS", default=not is_local_dev_environment()):
    app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1)
secret_key = os.getenv("SECRET_KEY")
if not secret_key:
    # Non-hardcoded fallback for local runs if .env is missing.
    secret_key = os.urandom(32).hex()
app.config["SECRET_KEY"] = secret_key
app.config["SESSION_COOKIE_HTTPONLY"] = True
app.config["SESSION_COOKIE_SAMESITE"] = "Lax"
session_cookie_secure_override = os.getenv("SESSION_COOKIE_SECURE")
if session_cookie_secure_override is None:
    # Safe default: secure cookies in deployed/server environments,
    # relaxed for explicit local/dev mode.
    session_cookie_secure = not is_local_dev_environment()
else:
    session_cookie_secure = env_bool("SESSION_COOKIE_SECURE", False)
app.config["SESSION_COOKIE_SECURE"] = session_cookie_secure
max_upload_mb = int(os.getenv("MAX_UPLOAD_MB", "4"))
app.config["MAX_CONTENT_LENGTH"] = max_upload_mb * 1024 * 1024

# Database URL placeholder flow:
# 1) Set DATABASE_URL in your environment for Postgres
# 2) If missing, fallback to local SQLite for development
database_url = os.getenv("DATABASE_URL", "sqlite:///FXJournal.db")
if database_url.startswith("postgres://"):
    database_url = database_url.replace("postgres://", "postgresql+psycopg://", 1)
elif database_url.startswith("postgresql://") and "+psycopg" not in database_url:
    database_url = database_url.replace("postgresql://", "postgresql+psycopg://", 1)

app.config["SQLALCHEMY_DATABASE_URI"] = database_url
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
db = SQLAlchemy(app)
csrf = CSRFProtect(app)
# For production, set RATELIMIT_STORAGE_URI to Redis for shared counters.
limiter = Limiter(
    key_func=get_remote_address,
    default_limits=[],
    storage_uri=os.getenv("RATELIMIT_STORAGE_URI", "memory://"),
)
limiter.init_app(app)

TOKEN_PURPOSE_VERIFY_EMAIL = "verify_email"
TOKEN_PURPOSE_PASSWORD_RESET = "password_reset"

BASE_SYMBOL_OPTIONS = [
    # Major FX
    "EURUSD",
    "GBPUSD",
    "USDJPY",
    "AUDUSD",
    "USDCAD",
    "USDCHF",
    "NZDUSD",
    # Minor/Cross FX
    "EURJPY",
    "GBPJPY",
    "AUDJPY",
    "CADJPY",
    "CHFJPY",
    "NZDJPY",
    "EURGBP",
    "EURCHF",
    "EURAUD",
    "EURNZD",
    "EURCAD",
    "GBPCHF",
    "GBPAUD",
    "GBPCAD",
    "GBPNZD",
    "AUDCAD",
    "AUDCHF",
    "AUDNZD",
    "CADCHF",
    "NZDCHF",
    "NZDCAD",
    # Metals
    "XAUUSD",
    "XAGUSD",
    # Indices (canonical names)
    "US500",
    "NAS100",
    "US30",
    "GER40",
    "UK100",
    "FRA40",
    "EU50",
    "JP225",
    "HK50",
    "CHN50",
    "AUS200",
    "ESP35",
    "IT40",
]


SYMBOL_ALIASES = {
    # US indices aliases
    "SPX500": "US500",
    "SP500": "US500",
    "US500CASH": "US500",
    "US500INDEX": "US500",
    "US100": "NAS100",
    "USTEC": "NAS100",
    "NAS100CASH": "NAS100",
    "NASDAQ100": "NAS100",
    "DJ30": "US30",
    "DJIA": "US30",
    "WS30": "US30",
    "US30CASH": "US30",
    # EU/UK indices aliases
    "DE40": "GER40",
    "DAX40": "GER40",
    "GER30": "GER40",
    "DE30": "GER40",
    "DAX": "GER40",
    "FTSE100": "UK100",
    "UKX": "UK100",
    "U100": "UK100",
    "CAC40": "FRA40",
    "FR40": "FRA40",
    "STOXX50": "EU50",
    "EUSTX50": "EU50",
    "SX5E": "EU50",
    # Asia-Pacific indices aliases
    "N225": "JP225",
    "NI225": "JP225",
    "JP225CASH": "JP225",
    "HSI": "HK50",
    "HSI50": "HK50",
    "HK50CASH": "HK50",
    "CN50": "CHN50",
    "CHINA50": "CHN50",
    "CHINAA50": "CHN50",
    "A50": "CHN50",
    "AU200": "AUS200",
    "ASX200": "AUS200",
    "IBEX35": "ESP35",
    "ES35": "ESP35",
    "ITA40": "IT40",
    # FX minor symbol shorthand seen at some brokers
    "EU": "EURUSD",
    "GU": "GBPUSD",
    "UJ": "USDJPY",
}


def get_symbol_options(selected_symbol=None):
    options = list(BASE_SYMBOL_OPTIONS)
    selected = canonicalize_symbol(selected_symbol)
    if selected and selected not in options:
        options.insert(0, selected)
    return options


MT5_COLUMN_ALIASES = {
    "mt5_position": {"position", "position id", "position ticket", "ticket"},
    "symbol": {"symbol", "instrument"},
    "side": {"type", "deal", "side"},
    "lot_size": {"volume", "lots", "lot"},
    "entry_price": {"open price", "price", "entry price"},
    "exit_price": {"close price", "exit price", "price close"},
    "pnl": {"profit", "p/l", "pl", "net profit"},
    "opened_at": {"time", "date", "open time", "close time"},
}


def normalize_header_name(value):
    text = str(value or "").strip().lower()
    text = re.sub(r"[\s_/\\-]+", " ", text)
    text = re.sub(r"[^a-z0-9 ]", "", text)
    return " ".join(text.split())


def parse_side_value(value):
    text = str(value or "").strip().upper()
    if "BUY" in text:
        return "BUY"
    if "SELL" in text:
        return "SELL"
    return None


def parse_float_value(value):
    if value is None or value == "":
        return None
    if isinstance(value, (int, float)):
        return float(value)

    text = str(value).strip()
    text = text.replace(",", "")
    if text.startswith("(") and text.endswith(")"):
        text = f"-{text[1:-1]}"
    try:
        return float(text)
    except ValueError:
        return None


def parse_datetime_value(value):
    if value is None or value == "":
        return None
    if isinstance(value, datetime):
        return value

    text = str(value).strip()
    if not text:
        return None

    for fmt in (
        "%Y-%m-%d %H:%M:%S",
        "%Y-%m-%d %H:%M",
        "%Y.%m.%d %H:%M:%S",
        "%Y.%m.%d %H:%M",
        "%Y-%m-%d",
        "%d.%m.%Y %H:%M:%S",
        "%d.%m.%Y %H:%M",
        "%d.%m.%Y",
    ):
        try:
            return datetime.strptime(text, fmt)
        except ValueError:
            continue
    return None


def parse_mt5_position_value(value):
    if value is None:
        return None
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if value.is_integer():
            return str(int(value))
        return None

    text = str(value).strip()
    if not text:
        return None

    cleaned = text.replace(",", "")
    if re.fullmatch(r"\d+", cleaned):
        return cleaned
    if re.fullmatch(r"\d+\.0+", cleaned):
        return cleaned.split(".", 1)[0]
    return None


def build_import_signature(prefix="mt5"):
    timestamp = datetime.utcnow().strftime("%Y%m%d%H%M%S")
    random_tail = os.urandom(4).hex()
    return f"{prefix}_{timestamp}_{random_tail}"


def parse_import_signature_datetime(signature):
    text_value = str(signature or "").strip()
    match = re.match(r"^[A-Za-z0-9]+_(\d{14})_[0-9a-fA-F]+$", text_value)
    if not match:
        return None
    try:
        return datetime.strptime(match.group(1), "%Y%m%d%H%M%S")
    except ValueError:
        return None


MT5_SECTION_TITLES = {"positions", "orders", "deals", "results"}


def row_texts(row):
    return [str(cell).strip() for cell in row if cell is not None and str(cell).strip() != ""]


def find_section_row(rows, section_name):
    target = normalize_header_name(section_name)
    for idx, row in enumerate(rows):
        texts = row_texts(row)
        if len(texts) == 1 and normalize_header_name(texts[0]) == target:
            return idx
    return None


def is_section_title_row(row):
    texts = row_texts(row)
    if len(texts) != 1:
        return False
    return normalize_header_name(texts[0]) in MT5_SECTION_TITLES


def build_mt5_column_map(header_row):
    normalized = [normalize_header_name(cell) for cell in header_row]
    column_map = {}
    by_name = {}

    for idx, name in enumerate(normalized):
        if not name:
            continue
        by_name.setdefault(name, []).append(idx)
        for canonical, aliases in MT5_COLUMN_ALIASES.items():
            if canonical in column_map:
                continue
            if name in aliases:
                column_map[canonical] = idx
                break

    # MT5 report headers often repeat "Time" and "Price" in Positions.
    time_cols = by_name.get("time", [])
    price_cols = by_name.get("price", [])
    if "opened_at" not in column_map and time_cols:
        column_map["opened_at"] = time_cols[0]
    if "entry_price" not in column_map and price_cols:
        column_map["entry_price"] = price_cols[0]
    if "exit_price" not in column_map and len(price_cols) >= 2:
        column_map["exit_price"] = price_cols[1]

    return column_map


def parse_mt5_xlsx_stream(file_stream):
    workbook = load_workbook(file_stream, data_only=True, read_only=True)
    worksheet = workbook.active

    rows = list(worksheet.iter_rows(values_only=True))
    section_idx = find_section_row(rows, "positions")
    if section_idx is None:
        workbook.close()
        return [], 0, 0

    header_idx = None
    column_map = {}

    header_scan_end = min(section_idx + 10, len(rows))
    for idx in range(section_idx + 1, header_scan_end):
        detected = build_mt5_column_map(rows[idx])
        if (
            detected.get("symbol") is not None
            and detected.get("side") is not None
            and detected.get("lot_size") is not None
        ):
            header_idx = idx
            column_map = detected
            break

    if header_idx is None:
        workbook.close()
        return [], 0, 0

    parsed = []
    skipped = 0
    total = 0

    for row_idx in range(header_idx + 1, len(rows)):
        row = rows[row_idx]
        texts = row_texts(row)
        if not texts:
            continue
        if is_section_title_row(row):
            break

        total += 1

        def col(key):
            idx = column_map.get(key)
            if idx is None or idx >= len(row):
                return None
            return row[idx]

        symbol = canonicalize_symbol(col("symbol"))
        mt5_position_raw = col("mt5_position")
        mt5_position = parse_mt5_position_value(mt5_position_raw)
        side = parse_side_value(col("side"))
        lot_size = parse_float_value(col("lot_size"))
        entry_price = parse_float_value(col("entry_price"))
        exit_price = parse_float_value(col("exit_price"))
        pnl = parse_float_value(col("pnl"))
        opened_at = parse_datetime_value(col("opened_at"))

        if not symbol or not side or lot_size is None or entry_price is None:
            skipped += 1
            continue

        parsed.append(
            {
                "symbol": symbol,
                "mt5_position": mt5_position,
                "mt5_position_raw": mt5_position_raw,
                "side": side,
                "lot_size": lot_size,
                "entry_price": entry_price,
                "exit_price": exit_price,
                "pnl": pnl,
                "opened_at": opened_at,
            }
        )

    workbook.close()
    return parsed, total, skipped


INSTRUMENT_CONTRACT_SIZE = {
    # Metals (common CFD conventions)
    "XAUUSD": 100.0,
    "XAGUSD": 5000.0,
    # Indices (point value per lot; can vary by broker)
    "US500": 1.0,
    "NAS100": 1.0,
    "US30": 1.0,
    "GER40": 1.0,
    "UK100": 1.0,
    "FRA40": 1.0,
    "EU50": 1.0,
    "JP225": 1.0,
    "HK50": 1.0,
    "CHN50": 1.0,
    "AUS200": 1.0,
    "ESP35": 1.0,
    "IT40": 1.0,
}


def normalize_symbol(symbol):
    return "".join(ch for ch in (symbol or "").upper() if ch.isalnum())


def canonicalize_symbol(symbol):
    normalized = normalize_symbol(symbol)
    if not normalized:
        return ""
    return SYMBOL_ALIASES.get(normalized, normalized)


def is_fx_pair(symbol):
    sym = normalize_symbol(symbol)
    return len(sym) == 6 and sym.isalpha()


def get_contract_size(symbol):
    sym = normalize_symbol(symbol)
    if sym in INSTRUMENT_CONTRACT_SIZE:
        return INSTRUMENT_CONTRACT_SIZE[sym]
    if is_fx_pair(sym):
        return 100000.0
    return 1.0


def quote_to_usd_rate(symbol, reference_price):
    sym = normalize_symbol(symbol)
    if sym.endswith("USD"):
        return 1.0

    # USDXXX pairs can be inverted to convert quote currency to USD.
    if is_fx_pair(sym) and sym.startswith("USD") and reference_price and reference_price > 0:
        return 1.0 / reference_price

    # Crosses like EURJPY need a separate conversion rate (not available here).
    return None


def get_pip_size(symbol):
    sym = normalize_symbol(symbol)
    if not is_fx_pair(sym):
        return None
    return 0.01 if sym.endswith("JPY") else 0.0001


def calc_pips_values(symbol, side, entry_price, exit_price):
    if entry_price is None or exit_price is None:
        return None

    pip_size = get_pip_size(symbol)
    if not pip_size:
        return None

    direction = 1.0 if (side or "").upper() == "BUY" else -1.0
    return direction * ((exit_price - entry_price) / pip_size)


def calc_pnl_values(symbol, side, entry_price, exit_price, lot_size):
    if entry_price is None or exit_price is None:
        return None
    if lot_size is None or lot_size <= 0:
        return None

    direction = 1.0 if (side or "").upper() == "BUY" else -1.0
    contract_size = get_contract_size(symbol)
    conversion_rate = quote_to_usd_rate(symbol, exit_price)
    if conversion_rate is None:
        return None

    return direction * (exit_price - entry_price) * lot_size * contract_size * conversion_rate


def derive_exit_price(symbol, side, entry_price, lot_size, pnl_value):
    if entry_price is None or pnl_value is None:
        return None
    if lot_size is None or lot_size <= 0:
        return None

    direction = 1.0 if (side or "").upper() == "BUY" else -1.0
    contract_size = get_contract_size(symbol)
    units = lot_size * contract_size
    if units <= 0:
        return None

    sym = normalize_symbol(symbol)

    # Quote currency is USD -> linear solve.
    if sym.endswith("USD"):
        return entry_price + (pnl_value / (direction * units))

    # USDXXX nonlinear solve:
    # pnl = direction * (exit-entry) * units / exit
    if is_fx_pair(sym) and sym.startswith("USD"):
        k = pnl_value / (direction * units)
        denom = 1.0 - k
        if abs(denom) < 1e-9:
            return None
        candidate = entry_price / denom
        return candidate if candidate > 0 else None

    return None


def calc_pnl(trade):
    return calc_pnl_values(
        symbol=trade.symbol,
        side=trade.side,
        entry_price=trade.entry_price,
        exit_price=trade.exit_price,
        lot_size=trade.lot_size,
    )


def resolve_pnl(trade):
    if trade.pnl is not None:
        return trade.pnl
    return calc_pnl(trade)


def resolve_pips(trade):
    return calc_pips_values(
        symbol=trade.symbol,
        side=trade.side,
        entry_price=trade.entry_price,
        exit_price=trade.exit_price,
    )


def build_dashboard_insight(user_trades, closed_trades):
    total_trades = len(user_trades)
    total_closed = len(closed_trades)
    insights = []

    symbol_counts = {}
    for trade in user_trades:
        symbol = (trade.symbol or "").strip().upper()
        if not symbol:
            continue
        symbol_counts[symbol] = symbol_counts.get(symbol, 0) + 1
    if symbol_counts:
        top_symbol, top_count = max(symbol_counts.items(), key=lambda item: (item[1], item[0]))
        top_share = (top_count / max(sum(symbol_counts.values()), 1)) * 100
        insights.append(
            {
                "title": "Most Traded Pair",
                "body": (
                    f"{top_symbol} is your most traded pair with {top_count} trades "
                    f"({top_share:.0f}% of your journal)."
                ),
            }
        )

    if total_closed >= 3:
        total_wins = sum(1 for _, pnl in closed_trades if pnl > 0)
        overall_win_rate = (total_wins / total_closed) * 100

        pair_stats = {}
        for trade, pnl in closed_trades:
            symbol = (trade.symbol or "").strip().upper()
            if not symbol:
                continue
            if symbol not in pair_stats:
                pair_stats[symbol] = {"count": 0, "wins": 0, "pnl_sum": 0.0}
            pair_stats[symbol]["count"] += 1
            pair_stats[symbol]["pnl_sum"] += float(pnl)
            if pnl > 0:
                pair_stats[symbol]["wins"] += 1

        eligible_pairs = [
            (symbol, stats) for symbol, stats in pair_stats.items() if stats["count"] >= 2
        ]
        if eligible_pairs:
            best_pair, best_stats = max(
                eligible_pairs,
                key=lambda item: (item[1]["wins"] / item[1]["count"], item[1]["count"]),
            )
            pair_win_rate = (best_stats["wins"] / best_stats["count"]) * 100
            pair_avg_pnl = best_stats["pnl_sum"] / best_stats["count"]
            if pair_win_rate > overall_win_rate:
                win_rate_delta = pair_win_rate - overall_win_rate
                insights.append(
                    {
                        "title": "Pair Edge",
                        "body": (
                            f"You perform {win_rate_delta:.1f}% better on {best_pair} by win rate "
                            f"({pair_win_rate:.1f}% vs {overall_win_rate:.1f}% overall)."
                        ),
                    }
                )
            insights.append(
                {
                    "title": "Pair Efficiency",
                    "body": (
                        f"Your average closed-trade result on {best_pair} is "
                        f"{pair_avg_pnl:+.2f} across {best_stats['count']} trades."
                    ),
                }
            )

    if total_closed >= 4:
        side_stats = {"BUY": {"count": 0, "pnl_sum": 0.0}, "SELL": {"count": 0, "pnl_sum": 0.0}}
        for trade, pnl in closed_trades:
            side = (trade.side or "").strip().upper()
            if side not in side_stats:
                continue
            side_stats[side]["count"] += 1
            side_stats[side]["pnl_sum"] += float(pnl)

        buy_count = side_stats["BUY"]["count"]
        sell_count = side_stats["SELL"]["count"]
        if buy_count >= 2 and sell_count >= 2:
            buy_avg = side_stats["BUY"]["pnl_sum"] / buy_count
            sell_avg = side_stats["SELL"]["pnl_sum"] / sell_count
            if abs(buy_avg - sell_avg) >= 0.01:
                better_side = "BUY" if buy_avg > sell_avg else "SELL"
                better_avg = buy_avg if buy_avg > sell_avg else sell_avg
                weaker_side = "SELL" if better_side == "BUY" else "BUY"
                weaker_avg = sell_avg if better_side == "BUY" else buy_avg
                insights.append(
                    {
                        "title": "Directional Bias",
                        "body": (
                            f"{better_side} setups outperform {weaker_side} "
                            f"({better_avg:+.2f} vs {weaker_avg:+.2f} average PnL per closed trade)."
                        ),
                    }
                )

    if total_closed >= 6:
        day_totals = {}
        for trade, pnl in closed_trades:
            if not trade.opened_at:
                continue
            day_key = trade.opened_at.strftime("%Y-%m-%d")
            if day_key not in day_totals:
                day_totals[day_key] = {"pnl_sum": 0.0, "count": 0}
            day_totals[day_key]["pnl_sum"] += float(pnl)
            day_totals[day_key]["count"] += 1

        if day_totals:
            trades_on_losing_days = sum(
                data["count"] for data in day_totals.values() if data["pnl_sum"] < 0
            )
            trades_on_non_losing_days = sum(
                data["count"] for data in day_totals.values() if data["pnl_sum"] >= 0
            )
            total_day_trades = trades_on_losing_days + trades_on_non_losing_days
            if (
                total_day_trades > 0
                and trades_on_losing_days > trades_on_non_losing_days
            ):
                losing_day_ratio = (trades_on_losing_days / total_day_trades) * 100
                insights.append(
                    {
                        "title": "Risk Pattern",
                        "body": (
                            f"{losing_day_ratio:.0f}% of your trades happen on net-losing days. "
                            "Consider reducing frequency after early losses."
                        ),
                    }
                )

    if total_trades == 0:
        return {
            "title": "No Data Yet",
            "body": "Add your first trade to unlock personalized performance insights.",
        }
    if not insights:
        return {
            "title": "Developing Edge",
            "body": (
                f"You've logged {total_trades} trades so far. "
                "As more closed trades accumulate, your insights will become more specific."
            ),
        }
    return random.choice(insights)


def get_public_base_url():
    configured_base = os.getenv("PUBLIC_BASE_URL", "").strip().rstrip("/")
    if configured_base:
        return configured_base
    return request.host_url.rstrip("/")


def build_external_url(path_or_url):
    if path_or_url.startswith("http://") or path_or_url.startswith("https://"):
        return path_or_url
    return f"{get_public_base_url()}{path_or_url}"


def get_token_serializer():
    token_salt = os.getenv("TOKEN_SALT", "fxjournal-token-salt")
    return URLSafeTimedSerializer(app.config["SECRET_KEY"], salt=token_salt)


def generate_auth_token(email, purpose):
    serializer = get_token_serializer()
    return serializer.dumps(
        {
            "email": (email or "").strip().lower(),
            "purpose": purpose,
        }
    )


def verify_auth_token(token, purpose, max_age_seconds):
    serializer = get_token_serializer()
    try:
        payload = serializer.loads(token, max_age=max_age_seconds)
    except (SignatureExpired, BadSignature):
        return None

    if not isinstance(payload, dict):
        return None
    if payload.get("purpose") != purpose:
        return None

    email = str(payload.get("email", "")).strip().lower()
    return email or None


def send_email_placeholder(to_email, subject, text_body):
    provider = os.getenv("EMAIL_PROVIDER", "placeholder").strip().lower()
    sender = os.getenv("EMAIL_FROM", "noreply@example.com").strip()
    send_enabled = env_bool("EMAIL_SEND_ENABLED", False)
    api_key = os.getenv("EMAIL_API_KEY", "").strip()

    if provider == "console" or not send_enabled:
        app.logger.info(
            "Email placeholder (console/disabled) -> to=%s from=%s subject=%s",
            to_email,
            sender,
            subject,
        )
        app.logger.info("Email body:\n%s", text_body)
        return {"sent": False, "mode": "placeholder"}

    if not api_key:
        app.logger.warning(
            "EMAIL_SEND_ENABLED is true but EMAIL_API_KEY is missing. Using placeholder mode."
        )
        app.logger.info("Email body:\n%s", text_body)
        return {"sent": False, "mode": "missing_api_key"}

    # Provider integration placeholder:
    # Add your provider client/request here (Resend, SendGrid, SES, etc).
    app.logger.warning(
        "Email provider '%s' is configured but integration is not implemented yet.", provider
    )
    app.logger.info("Email body:\n%s", text_body)
    return {"sent": False, "mode": "not_implemented"}


class User(db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(255), nullable=False)
    email_verified = db.Column(db.Boolean, nullable=False, default=False)
    verification_sent_at = db.Column(db.DateTime, nullable=True)
    trades = db.relationship("Trade", backref="user", lazy=True)


class Trade(db.Model):
    __tablename__ = "trades"

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False, index=True)
    symbol = db.Column(db.String(20), nullable=False, default="EURUSD")
    side = db.Column(db.String(10), nullable=False, default="BUY")
    entry_price = db.Column(db.Float, nullable=False, default=0.0)
    exit_price = db.Column(db.Float, nullable=True)
    lot_size = db.Column(db.Float, nullable=False, default=0.01)
    pnl = db.Column(db.Float, nullable=True)
    mt5_position = db.Column(db.String(64), nullable=True, index=True)
    import_signature = db.Column(db.String(80), nullable=True, index=True)
    trade_note = db.Column(db.Text, nullable=True)
    opened_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)


def ensure_trades_table_columns():
    table_name = Trade.__tablename__
    inspector = inspect(db.engine)
    if table_name not in inspector.get_table_names():
        return

    existing_columns = {col["name"] for col in inspector.get_columns(table_name)}
    statements = []
    if "mt5_position" not in existing_columns:
        statements.append(
            f"ALTER TABLE {table_name} ADD COLUMN mt5_position VARCHAR(64)"
        )
    if "import_signature" not in existing_columns:
        statements.append(
            f"ALTER TABLE {table_name} ADD COLUMN import_signature VARCHAR(80)"
        )

    with db.engine.begin() as connection:
        for stmt in statements:
            connection.execute(text(stmt))
        connection.execute(
            text(
                "CREATE INDEX IF NOT EXISTS ix_trades_user_mt5_position "
                f"ON {table_name} (user_id, mt5_position)"
            )
        )
        connection.execute(
            text(
                "CREATE INDEX IF NOT EXISTS ix_trades_user_import_signature "
                f"ON {table_name} (user_id, import_signature)"
            )
        )


def ensure_users_table_columns():
    table_name = User.__tablename__
    inspector = inspect(db.engine)
    if table_name not in inspector.get_table_names():
        return

    existing_columns = {col["name"] for col in inspector.get_columns(table_name)}
    statements = []
    if "email_verified" not in existing_columns:
        statements.append(
            f"ALTER TABLE {table_name} ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT FALSE"
        )
    if "verification_sent_at" not in existing_columns:
        statements.append(
            f"ALTER TABLE {table_name} ADD COLUMN verification_sent_at TIMESTAMP"
        )

    with db.engine.begin() as connection:
        for stmt in statements:
            connection.execute(text(stmt))


with app.app_context():
    db.create_all()
    ensure_users_table_columns()
    ensure_trades_table_columns()


def _is_same_origin(url_value):
    parsed = urlparse(url_value)
    if parsed.scheme not in {"http", "https"}:
        return False
    return parsed.netloc == request.host


@app.before_request
def enforce_same_origin_for_authenticated_posts():
    if request.method != "POST":
        return None
    if not session.get("user_id"):
        return None

    origin = request.headers.get("Origin", "").strip()
    referer = request.headers.get("Referer", "").strip()
    if origin and not _is_same_origin(origin):
        return "Forbidden", 403
    if not origin and referer and not _is_same_origin(referer):
        return "Forbidden", 403
    return None


@app.after_request
def set_security_headers(response):
    response.headers.setdefault("X-Content-Type-Options", "nosniff")
    response.headers.setdefault("X-Frame-Options", "SAMEORIGIN")
    response.headers.setdefault("Referrer-Policy", "strict-origin-when-cross-origin")
    return response


@app.errorhandler(RequestEntityTooLarge)
def handle_large_upload(_error):
    if session.get("user_id"):
        return redirect(
            url_for(
                "new_trade",
                import_status="error",
                import_message=f"File too large. Max upload is {max_upload_mb} MB.",
            )
        )
    return redirect(url_for("login"))


@app.errorhandler(429)
def handle_rate_limit(_error):
    if request.path == "/login":
        created = request.args.get("created") == "1"
        return (
            render_template(
                "login.html",
                title="Login | FX Journal",
                body_class="auth-layout",
                error="Too many login attempts. Please wait a minute and try again.",
                success="Account created. Please log in." if created else None,
            ),
            429,
        )
    return "Too many requests. Please try again later.", 429


@app.route("/")
def home():
    if not session.get("user_id"):
        return redirect(url_for("login"))

    username = session.get("username", "User")
    user_id = session["user_id"]

    try:
        user_trades = (
            Trade.query.filter_by(user_id=user_id)
            .order_by(Trade.opened_at.desc())
            .all()
        )
    except OperationalError:
        db.session.rollback()
        user_trades = []

    now = datetime.utcnow()
    week_start = (now - timedelta(days=now.weekday())).replace(
        hour=0, minute=0, second=0, microsecond=0
    )

    closed = []
    for trade in user_trades:
        pnl_value = resolve_pnl(trade)
        if pnl_value is not None:
            closed.append((trade, pnl_value))

    total_closed = len(closed)
    wins = sum(1 for _, pnl in closed if pnl > 0)
    losses = sum(1 for _, pnl in closed if pnl < 0)
    win_rate = (wins / total_closed * 100) if total_closed else 0.0

    net_pnl_week = sum(
        pnl for trade, pnl in closed if trade.opened_at and trade.opened_at >= week_start
    )
    trades_this_month = sum(
        1
        for trade in user_trades
        if trade.opened_at
        and trade.opened_at.month == now.month
        and trade.opened_at.year == now.year
    )

    avg_win = (sum(p for _, p in closed if p > 0) / wins) if wins else 0
    avg_loss = (abs(sum(p for _, p in closed if p < 0)) / losses) if losses else 0
    avg_rr = (avg_win / avg_loss) if avg_loss else None
    account_pnl_total = sum(pnl for _, pnl in closed)

    recent_trades = []
    for trade in user_trades:
        pnl_value = resolve_pnl(trade)
        pips_value = resolve_pips(trade)
        trade_date = trade.opened_at.strftime("%d %b %Y") if trade.opened_at else "-"
        trade_date_value = trade.opened_at.strftime("%Y-%m-%d") if trade.opened_at else ""
        recent_trades.append(
            {
                "symbol": trade.symbol,
                "side": trade.side,
                "entry_price": trade.entry_price,
                "exit_price": trade.exit_price,
                "lot_size": trade.lot_size,
                "pnl": pnl_value,
                "pips": pips_value,
                "date": trade_date,
                "date_value": trade_date_value,
                "status": "Closed" if trade.exit_price is not None else "Running",
            }
        )

    chart_points = []
    closed_for_equity = sorted(
        closed,
        key=lambda item: (
            item[0].opened_at or datetime.min,
            item[0].id or 0,
        ),
    )
    running_equity = 0.0
    daily_equity_points = {}
    for trade, pnl in closed_for_equity:
        running_equity += float(pnl)
        if not trade.opened_at:
            continue
        day_key = trade.opened_at.strftime("%Y-%m-%d")
        daily_equity_points[day_key] = {
            "date": day_key,
            "label": trade.opened_at.strftime("%d %b"),
            "equity": round(running_equity, 2),
        }
    chart_points = list(daily_equity_points.values())
    dashboard_insight = build_dashboard_insight(user_trades, closed)

    return render_template(
        "index.html",
        title="FX Journal",
        username=username,
        win_rate=win_rate,
        net_pnl_week=net_pnl_week,
        account_pnl_total=account_pnl_total,
        trades_this_month=trades_this_month,
        avg_rr=avg_rr,
        recent_trades=recent_trades,
        chart_points=chart_points,
        dashboard_insight=dashboard_insight,
    )


@app.route("/login", methods=["GET", "POST"])
@limiter.limit(
    "8 per minute;40 per hour",
    methods=["POST"],
    error_message="Too many login attempts. Please wait and try again.",
)
def login():
    if session.get("user_id"):
        return redirect(url_for("home"))

    verified = request.args.get("verified") == "1"
    reset_done = request.args.get("reset") == "1"
    success_message = request.args.get("success", "").strip()

    if not success_message:
        if reset_done:
            success_message = "Password reset successful. Please log in."
        elif verified:
            success_message = "Email verified. You can now log in."

    if request.method == "POST":
        email = request.form.get("email", "").strip().lower()
        password = request.form.get("password", "")

        user = User.query.filter_by(email=email).first()
        if user and check_password_hash(user.password, password):
            if env_bool("REQUIRE_EMAIL_VERIFICATION", True) and not user.email_verified:
                return render_template(
                    "login.html",
                    title="Login | FX Journal",
                    body_class="auth-layout",
                    error="Please verify your email before logging in.",
                    success=success_message,
                )
            session["user_id"] = user.id
            session["username"] = user.username
            return redirect(url_for("home"))

        return render_template(
            "login.html",
            title="Login | FX Journal",
            body_class="auth-layout",
            error="Invalid email or password.",
            success=success_message,
        )
    return render_template(
        "login.html",
        title="Login | FX Journal",
        body_class="auth-layout",
        success=success_message,
    )


@app.route("/register", methods=["GET", "POST"])
def register():
    if session.get("user_id"):
        return redirect(url_for("home"))

    created = request.args.get("created") == "1"
    success_message = request.args.get("success", "").strip()
    verify_link = request.args.get("verify_link", "").strip()
    if not success_message and created:
        success_message = "Verification email sent. Please verify your email before logging in."

    if request.method == "POST":
        username = request.form.get("username", "").strip()
        email = request.form.get("email", "").strip().lower()
        password = request.form.get("password", "")

        if not username or not email or not password:
            return render_template(
                "register.html",
                title="Register | FX Journal",
                body_class="auth-layout",
                error="All fields are required.",
                success=success_message or None,
                verify_link=verify_link,
            )

        existing_user = User.query.filter(
            or_(User.username == username, User.email == email)
        ).first()
        if existing_user:
            return render_template(
                "register.html",
                title="Register | FX Journal",
                body_class="auth-layout",
                error="Username or email already exists.",
                success=success_message or None,
                verify_link=verify_link,
            )

        hashed_password = generate_password_hash(password)
        user = User(
            username=username,
            email=email,
            password=hashed_password,
            email_verified=False,
            verification_sent_at=datetime.utcnow(),
        )
        db.session.add(user)
        db.session.commit()

        verify_token = generate_auth_token(email=email, purpose=TOKEN_PURPOSE_VERIFY_EMAIL)
        verify_link = build_external_url(
            url_for("verify_email_token", token=verify_token)
        )
        email_subject = "Verify your FX Journal email"
        email_body = (
            f"Hi {username},\n\n"
            "Thanks for registering.\n"
            "Verify your email by opening this link:\n"
            f"{verify_link}\n\n"
            "If you did not create this account, you can ignore this email."
        )
        email_result = send_email_placeholder(email, email_subject, email_body)

        register_kwargs = {"created": "1"}
        if is_local_dev_environment() and not email_result.get("sent"):
            register_kwargs["verify_link"] = verify_link
        return redirect(url_for("register", **register_kwargs))

    return render_template(
        "register.html",
        title="Register | FX Journal",
        body_class="auth-layout",
        success=success_message or None,
        verify_link=verify_link,
    )


@app.route("/verify-email/resend", methods=["GET", "POST"])
@limiter.limit(
    "5 per minute;20 per hour",
    methods=["POST"],
    error_message="Too many attempts. Please wait and try again.",
)
def resend_verification_email():
    success = ""
    error = ""
    debug_verify_link = ""

    if request.method == "POST":
        email = request.form.get("email", "").strip().lower()
        generic_success = (
            "If this email exists, a verification link has been sent."
        )
        if not email:
            error = "Email is required."
        else:
            user = User.query.filter_by(email=email).first()
            if user and not user.email_verified:
                verify_token = generate_auth_token(
                    email=user.email,
                    purpose=TOKEN_PURPOSE_VERIFY_EMAIL,
                )
                verify_link = build_external_url(
                    url_for("verify_email_token", token=verify_token)
                )
                email_subject = "Verify your FX Journal email"
                email_body = (
                    f"Hi {user.username},\n\n"
                    "You requested a new verification link.\n"
                    f"{verify_link}\n\n"
                    "If you did not request this, you can ignore this email."
                )
                email_result = send_email_placeholder(user.email, email_subject, email_body)
                user.verification_sent_at = datetime.utcnow()
                db.session.commit()
                if is_local_dev_environment() and not email_result.get("sent"):
                    debug_verify_link = verify_link
            success = generic_success

    return render_template(
        "resend_verification.html",
        title="Resend Verification | FX Journal",
        body_class="auth-layout",
        success=success or None,
        error=error or None,
        debug_verify_link=debug_verify_link,
    )


@app.route("/verify-email/<token>")
def verify_email_token(token):
    max_age_seconds = env_int("EMAIL_VERIFY_TOKEN_MAX_AGE_SECONDS", 86400)
    email = verify_auth_token(
        token=token,
        purpose=TOKEN_PURPOSE_VERIFY_EMAIL,
        max_age_seconds=max_age_seconds,
    )
    if not email:
        return redirect(
            url_for(
                "login",
                success="Verification link is invalid or expired. Request a new one.",
            )
        )

    user = User.query.filter_by(email=email).first()
    if not user:
        return redirect(url_for("login", success="Verification completed. Please log in."))

    if not user.email_verified:
        user.email_verified = True
        db.session.commit()

    return redirect(url_for("login", verified="1"))


@app.route("/password/forgot", methods=["GET", "POST"])
@limiter.limit(
    "5 per minute;20 per hour",
    methods=["POST"],
    error_message="Too many attempts. Please wait and try again.",
)
def forgot_password():
    success = ""
    error = ""
    debug_reset_link = ""

    if request.method == "POST":
        email = request.form.get("email", "").strip().lower()
        generic_success = (
            "If this email exists, a password reset link has been sent."
        )
        if not email:
            error = "Email is required."
        else:
            user = User.query.filter_by(email=email).first()
            if user:
                reset_token = generate_auth_token(
                    email=user.email,
                    purpose=TOKEN_PURPOSE_PASSWORD_RESET,
                )
                reset_link = build_external_url(
                    url_for("reset_password_token", token=reset_token)
                )
                email_subject = "Reset your FX Journal password"
                email_body = (
                    f"Hi {user.username},\n\n"
                    "You requested a password reset.\n"
                    "Open this link to set a new password:\n"
                    f"{reset_link}\n\n"
                    "If you did not request this, you can ignore this email."
                )
                email_result = send_email_placeholder(user.email, email_subject, email_body)
                if is_local_dev_environment() and not email_result.get("sent"):
                    debug_reset_link = reset_link
            success = generic_success

    return render_template(
        "forgot_password.html",
        title="Forgot Password | FX Journal",
        body_class="auth-layout",
        success=success or None,
        error=error or None,
        debug_reset_link=debug_reset_link,
    )


@app.route("/password/reset/<token>", methods=["GET", "POST"])
def reset_password_token(token):
    max_age_seconds = env_int("PASSWORD_RESET_TOKEN_MAX_AGE_SECONDS", 3600)
    email = verify_auth_token(
        token=token,
        purpose=TOKEN_PURPOSE_PASSWORD_RESET,
        max_age_seconds=max_age_seconds,
    )
    if not email:
        return render_template(
            "reset_password.html",
            title="Reset Password | FX Journal",
            body_class="auth-layout",
            error="Reset link is invalid or expired.",
            token_valid=False,
        )

    user = User.query.filter_by(email=email).first()
    if not user:
        return render_template(
            "reset_password.html",
            title="Reset Password | FX Journal",
            body_class="auth-layout",
            error="Reset link is invalid or expired.",
            token_valid=False,
        )

    if request.method == "POST":
        new_password = request.form.get("password", "")
        confirm_password = request.form.get("confirm_password", "")

        if not new_password or not confirm_password:
            return render_template(
                "reset_password.html",
                title="Reset Password | FX Journal",
                body_class="auth-layout",
                error="Both password fields are required.",
                token_valid=True,
            )
        if new_password != confirm_password:
            return render_template(
                "reset_password.html",
                title="Reset Password | FX Journal",
                body_class="auth-layout",
                error="Passwords do not match.",
                token_valid=True,
            )
        if len(new_password) < 8:
            return render_template(
                "reset_password.html",
                title="Reset Password | FX Journal",
                body_class="auth-layout",
                error="Password must be at least 8 characters.",
                token_valid=True,
            )

        user.password = generate_password_hash(new_password)
        db.session.commit()
        return redirect(url_for("login", reset="1"))

    return render_template(
        "reset_password.html",
        title="Reset Password | FX Journal",
        body_class="auth-layout",
        token_valid=True,
    )


@app.route("/logout", methods=["POST"])
def logout():
    session.clear()
    return redirect(url_for("login"))


@app.route("/account", methods=["GET", "POST"])
def account():
    if not session.get("user_id"):
        return redirect(url_for("login"))

    user = User.query.filter_by(id=session["user_id"]).first_or_404()

    if request.method == "POST":
        username = request.form.get("username", "").strip()
        email = request.form.get("email", "").strip().lower()
        current_password = request.form.get("current_password", "")
        new_password = request.form.get("new_password", "")
        confirm_new_password = request.form.get("confirm_new_password", "")

        if not username or not email:
            return redirect(
                url_for(
                    "account",
                    account_status="error",
                    account_message="Username and email are required.",
                )
            )

        conflicting_user = User.query.filter(
            User.id != user.id,
            or_(User.username == username, User.email == email),
        ).first()
        if conflicting_user:
            return redirect(
                url_for(
                    "account",
                    account_status="error",
                    account_message="Username or email is already in use.",
                )
            )

        password_update_requested = any(
            [current_password, new_password, confirm_new_password]
        )
        if password_update_requested:
            if not all([current_password, new_password, confirm_new_password]):
                return redirect(
                    url_for(
                        "account",
                        account_status="error",
                        account_message="To change password, fill current, new, and confirm fields.",
                    )
                )
            if not check_password_hash(user.password, current_password):
                return redirect(
                    url_for(
                        "account",
                        account_status="error",
                        account_message="Current password is incorrect.",
                    )
                )
            if new_password != confirm_new_password:
                return redirect(
                    url_for(
                        "account",
                        account_status="error",
                        account_message="New password and confirmation do not match.",
                    )
                )
            if len(new_password) < 8:
                return redirect(
                    url_for(
                        "account",
                        account_status="error",
                        account_message="New password must be at least 8 characters.",
                    )
                )
            user.password = generate_password_hash(new_password)

        username_changed = user.username != username
        user.username = username
        user.email = email

        try:
            db.session.commit()
        except OperationalError:
            db.session.rollback()
            return redirect(
                url_for(
                    "account",
                    account_status="error",
                    account_message="Could not save account changes. Please try again.",
                )
            )

        if username_changed:
            session["username"] = username

        success_message = "Account details updated."
        if password_update_requested:
            success_message = "Account details and password updated."
        return redirect(
            url_for(
                "account",
                account_status="success",
                account_message=success_message,
            )
        )

    account_status = request.args.get("account_status", "").strip().lower()
    account_message = request.args.get("account_message", "").strip()
    if account_status not in {"success", "error", "info"}:
        account_status = ""
    if not account_message:
        account_status = ""

    total_trades = Trade.query.filter_by(user_id=user.id).count()
    closed_trades = (
        Trade.query.filter_by(user_id=user.id)
        .filter(Trade.exit_price.isnot(None))
        .count()
    )
    imported_trades = (
        Trade.query.filter_by(user_id=user.id)
        .filter(Trade.import_signature.isnot(None))
        .count()
    )

    return render_template(
        "account.html",
        title="My Account | FX Journal",
        username=session.get("username", "User"),
        account_user=user,
        email_verified=bool(user.email_verified),
        account_status=account_status,
        account_message=account_message,
        total_trades=total_trades,
        closed_trades=closed_trades,
        running_trades=max(total_trades - closed_trades, 0),
        imported_trades=imported_trades,
    )


@app.route("/trades")
def trades():
    if not session.get("user_id"):
        return redirect(url_for("login"))

    username = session.get("username", "User")
    user_id = session["user_id"]
    try:
        user_trades = (
            Trade.query.filter_by(user_id=user_id)
            .order_by(Trade.opened_at.desc())
            .all()
        )
    except OperationalError:
        db.session.rollback()
        user_trades = []

    trade_rows = []
    for trade in user_trades:
        trade_rows.append(
            {
                "id": trade.id,
                "symbol": trade.symbol,
                "side": trade.side,
                "entry_price": trade.entry_price,
                "exit_price": trade.exit_price,
                "lot_size": trade.lot_size,
                "pnl": resolve_pnl(trade),
                "pips": resolve_pips(trade),
                "opened_at": trade.opened_at,
            }
        )

    batch_delete_status = request.args.get("batch_delete_status", "").strip().lower()
    batch_delete_message = request.args.get("batch_delete_message", "").strip()
    if batch_delete_status not in {"success", "error", "info"}:
        batch_delete_status = ""
    if not batch_delete_message:
        batch_delete_status = ""

    import_batch_map = {}
    for trade in user_trades:
        signature = (trade.import_signature or "").strip()
        if not signature:
            continue
        if signature not in import_batch_map:
            imported_at = parse_import_signature_datetime(signature)
            import_batch_map[signature] = {
                "signature": signature,
                "trade_count": 0,
                "imported_at": imported_at,
                "imported_at_label": (
                    imported_at.strftime("%Y-%m-%d %H:%M UTC")
                    if imported_at
                    else "Unknown import time"
                ),
            }
        import_batch_map[signature]["trade_count"] += 1

    import_batches = sorted(
        import_batch_map.values(),
        key=lambda batch: batch["imported_at"] or datetime.min,
        reverse=True,
    )

    return render_template(
        "trades.html",
        title="My Trades | FX Journal",
        username=username,
        trades=trade_rows,
        import_batches=import_batches,
        batch_delete_status=batch_delete_status,
        batch_delete_message=batch_delete_message,
    )

@app.route("/trades/new", methods=["GET", "POST"])
def new_trade():
    if not session.get("user_id"):
        return redirect(url_for("login"))

    if request.method == "POST":
        allowed_symbols = set(get_symbol_options())
        symbol = canonicalize_symbol(request.form.get("symbol", ""))
        if symbol not in allowed_symbols:
            return redirect(url_for("new_trade"))
        side = request.form.get("side", "BUY").strip().upper()
        entry_price = float(request.form.get("entry_price", 0.0))
        exit_price = request.form.get("exit_price", "").strip()
        exit_price = float(exit_price) if exit_price else None
        lot_size = float(request.form.get("lot_size", 0.01))
        trade_note = request.form.get("trade_note", "").strip()
        pnl = request.form.get("pnl", "").strip()
        pnl = float(pnl) if pnl else None
        trade_date_raw = request.form.get("trade_date", "").strip()
        try:
            opened_at = (
                datetime.strptime(trade_date_raw, "%Y-%m-%d")
                if trade_date_raw
                else datetime.utcnow()
            )
        except ValueError:
            opened_at = datetime.utcnow()

        if pnl is not None and exit_price is None:
            exit_price = derive_exit_price(
                symbol=symbol,
                side=side,
                entry_price=entry_price,
                lot_size=lot_size,
                pnl_value=pnl,
            )
        if pnl is None and exit_price is not None:
            pnl = calc_pnl_values(
                symbol=symbol,
                side=side,
                entry_price=entry_price,
                exit_price=exit_price,
                lot_size=lot_size,
            )
        trade = Trade(
            user_id=session["user_id"],
            symbol=symbol,
            side=side,
            entry_price=entry_price,
            lot_size=lot_size,
            trade_note=trade_note,
            pnl=pnl,
            exit_price=exit_price,
            opened_at=opened_at,
        )
        db.session.add(trade)
        db.session.commit()
        return redirect(url_for("trades"))

    import_status = request.args.get("import_status", "").strip().lower()
    import_message = request.args.get("import_message", "").strip()
    if import_status not in {"success", "error", "info"}:
        import_status = ""
    if not import_message:
        import_status = ""

    return render_template(
        "trade_entry.html",
        title="New Trade | FX Journal",
        username=session.get("username", "User"),
        symbol_options=get_symbol_options(),
        import_status=import_status,
        import_message=import_message,
        trade=None,
        form_action=url_for("new_trade"),
        form_mode="new",
    )


@app.route("/import", methods=["POST"])
def import_mt5_trades():
    if not session.get("user_id"):
        return redirect(url_for("login"))

    uploaded_file = request.files.get("mt5_file")
    if not uploaded_file or not uploaded_file.filename:
        return redirect(
            url_for(
                "new_trade",
                import_status="error",
                import_message="Please choose an MT5 .xlsx file to upload.",
            )
        )

    filename = uploaded_file.filename.strip().lower()
    if not filename.endswith(".xlsx"):
        return redirect(
            url_for(
                "new_trade",
                import_status="error",
                import_message="Invalid file type. Please upload an .xlsx file.",
            )
        )

    try:
        uploaded_file.stream.seek(0)
        parsed_rows, total_rows, skipped_rows = parse_mt5_xlsx_stream(uploaded_file.stream)
        if not parsed_rows:
            return redirect(
                url_for(
                    "new_trade",
                    import_status="error",
                    import_message="No valid trade rows found in this MT5 file.",
                )
            )

        user_id = session["user_id"]
        allowed_symbols = set(BASE_SYMBOL_OPTIONS)
        failed_symbols = set()
        validation_skipped = 0
        validation_reasons = {
            "missing_mt5_position": 0,
            "invalid_mt5_position": 0,
            "invalid_side": 0,
            "invalid_entry_or_lot": 0,
            "invalid_exit_price": 0,
            "missing_open_time": 0,
        }

        existing_positions = {
            pos
            for (pos,) in db.session.query(Trade.mt5_position)
            .filter_by(user_id=user_id)
            .filter(Trade.mt5_position.isnot(None))
            .all()
            if pos
        }

        import_positions = set()
        import_signature = build_import_signature("mt5")
        duplicate_count = 0
        insert_batch = []

        for row in parsed_rows:
            symbol = canonicalize_symbol(row.get("symbol"))
            mt5_position = row.get("mt5_position")
            mt5_position_raw = row.get("mt5_position_raw")
            side = (row.get("side") or "").upper()
            lot_size = row.get("lot_size")
            entry_price = row.get("entry_price")
            exit_price = row.get("exit_price")
            pnl = row.get("pnl")
            opened_at = row.get("opened_at")

            if symbol not in allowed_symbols:
                if symbol:
                    failed_symbols.add(symbol)
                validation_skipped += 1
                continue

            if mt5_position is None:
                validation_skipped += 1
                raw_text = str(mt5_position_raw or "").strip()
                if raw_text:
                    validation_reasons["invalid_mt5_position"] += 1
                else:
                    validation_reasons["missing_mt5_position"] += 1
                continue

            if side not in {"BUY", "SELL"}:
                validation_skipped += 1
                validation_reasons["invalid_side"] += 1
                continue

            if lot_size is None or lot_size <= 0 or entry_price is None or entry_price <= 0:
                validation_skipped += 1
                validation_reasons["invalid_entry_or_lot"] += 1
                continue

            if exit_price is not None and exit_price <= 0:
                validation_skipped += 1
                validation_reasons["invalid_exit_price"] += 1
                continue

            if opened_at is None:
                validation_skipped += 1
                validation_reasons["missing_open_time"] += 1
                continue

            if pnl is None and exit_price is not None:
                pnl = calc_pnl_values(symbol, side, entry_price, exit_price, lot_size)

            if mt5_position in existing_positions or mt5_position in import_positions:
                duplicate_count += 1
                continue

            import_positions.add(mt5_position)
            insert_batch.append(
                Trade(
                    user_id=user_id,
                    symbol=symbol,
                    mt5_position=mt5_position,
                    import_signature=import_signature,
                    side=side,
                    entry_price=float(entry_price),
                    exit_price=float(exit_price) if exit_price is not None else None,
                    lot_size=float(lot_size),
                    pnl=float(pnl) if pnl is not None else None,
                    opened_at=opened_at,
                    trade_note="Imported from MT5 Positions",
                )
            )

        if not insert_batch:
            symbol_msg = ""
            if failed_symbols:
                failed_list = sorted(failed_symbols)
                shown = ", ".join(failed_list[:8])
                extra = len(failed_list) - 8
                if extra > 0:
                    shown = f"{shown}, +{extra} more"
                symbol_msg = f" Unrecognized symbols: {shown}."
            return redirect(
                url_for(
                    "new_trade",
                    import_status="error",
                    import_message=(
                        f"No trades imported. Parsed {len(parsed_rows)} rows, "
                        f"skipped {skipped_rows + validation_skipped + duplicate_count}."
                        f"{symbol_msg}"
                    ),
                )
            )

        db.session.add_all(insert_batch)
        db.session.commit()

        status = "success"
        if failed_symbols:
            status = "error"
        elif skipped_rows or validation_skipped or duplicate_count:
            status = "info"

        symbol_msg = ""
        if failed_symbols:
            failed_list = sorted(failed_symbols)
            shown = ", ".join(failed_list[:8])
            extra = len(failed_list) - 8
            if extra > 0:
                shown = f"{shown}, +{extra} more"
            symbol_msg = f" Unrecognized symbols skipped: {shown}."

        uncertain_bits = []
        if validation_reasons["missing_mt5_position"]:
            uncertain_bits.append(
                f"missing MT5 position {validation_reasons['missing_mt5_position']}"
            )
        if validation_reasons["invalid_mt5_position"]:
            uncertain_bits.append(
                f"invalid MT5 position {validation_reasons['invalid_mt5_position']}"
            )
        if validation_reasons["invalid_side"]:
            uncertain_bits.append(f"invalid side {validation_reasons['invalid_side']}")
        if validation_reasons["invalid_entry_or_lot"]:
            uncertain_bits.append(f"invalid entry/lot {validation_reasons['invalid_entry_or_lot']}")
        if validation_reasons["invalid_exit_price"]:
            uncertain_bits.append(f"invalid exit price {validation_reasons['invalid_exit_price']}")
        if validation_reasons["missing_open_time"]:
            uncertain_bits.append(f"missing open time {validation_reasons['missing_open_time']}")
        uncertain_msg = ""
        if uncertain_bits:
            uncertain_msg = " Data uncertainty checks: " + ", ".join(uncertain_bits) + "."

        return redirect(
            url_for(
                "new_trade",
                import_status=status,
                import_message=(
                    f"Imported {len(insert_batch)} trades from Positions. "
                    f"Parsed rows: {len(parsed_rows)}/{total_rows}. "
                    f"Skipped: {skipped_rows + validation_skipped}. "
                    f"Duplicate positions: {duplicate_count}."
                    f" Import signature: {import_signature}."
                    f"{symbol_msg}"
                    f"{uncertain_msg}"
                ),
            )
        )
    except Exception:
        db.session.rollback()
        return redirect(
            url_for(
                "new_trade",
                import_status="error",
                import_message="Upload processing failed. Check MT5 export format and try again.",
            )
        )


@app.route("/trades/<int:trade_id>")
def trade_detail(trade_id):
    if not session.get("user_id"):
        return redirect(url_for("login"))

    trade = Trade.query.filter_by(id=trade_id, user_id=session["user_id"]).first_or_404()
    trade_pnl = resolve_pnl(trade)
    trade_pips = resolve_pips(trade)

    return render_template(
        "trade_detail.html",
        title="Trade Detail | FX Journal",
        username=session.get("username", "User"),
        trade=trade,
        trade_pnl=trade_pnl,
        trade_pips=trade_pips,
    )


@app.route("/trades/<int:trade_id>/edit", methods=["GET", "POST"])
def edit_trade(trade_id):
    if not session.get("user_id"):
        return redirect(url_for("login"))

    trade = Trade.query.filter_by(id=trade_id, user_id=session["user_id"]).first_or_404()

    if request.method == "POST":
        allowed_symbols = set(get_symbol_options(trade.symbol))
        symbol = canonicalize_symbol(request.form.get("symbol", ""))
        if symbol not in allowed_symbols:
            return redirect(url_for("edit_trade", trade_id=trade.id))
        side = request.form.get("side", "BUY").strip().upper()
        entry_price = float(request.form.get("entry_price", 0.0))
        exit_price = request.form.get("exit_price", "").strip()
        exit_price = float(exit_price) if exit_price else None
        lot_size = float(request.form.get("lot_size", 0.01))
        trade_note = request.form.get("trade_note", "").strip()
        pnl = request.form.get("pnl", "").strip()
        pnl = float(pnl) if pnl else None
        trade_date_raw = request.form.get("trade_date", "").strip()
        try:
            opened_at = (
                datetime.strptime(trade_date_raw, "%Y-%m-%d")
                if trade_date_raw
                else trade.opened_at
            )
        except ValueError:
            opened_at = trade.opened_at

        if pnl is not None and exit_price is None:
            exit_price = derive_exit_price(
                symbol=symbol,
                side=side,
                entry_price=entry_price,
                lot_size=lot_size,
                pnl_value=pnl,
            )
        if pnl is None and exit_price is not None:
            pnl = calc_pnl_values(
                symbol=symbol,
                side=side,
                entry_price=entry_price,
                exit_price=exit_price,
                lot_size=lot_size,
            )

        trade.symbol = symbol
        trade.side = side
        trade.entry_price = entry_price
        trade.exit_price = exit_price
        trade.lot_size = lot_size
        trade.trade_note = trade_note
        trade.pnl = pnl
        trade.opened_at = opened_at

        db.session.commit()
        return redirect(url_for("trades"))

    return render_template(
        "trade_entry.html",
        title="Edit Trade | FX Journal",
        username=session.get("username", "User"),
        symbol_options=get_symbol_options(trade.symbol),
        trade=trade,
        form_action=url_for("edit_trade", trade_id=trade.id),
        form_mode="edit",
    )


@app.route("/trades/<int:trade_id>/delete", methods=["POST"])
def delete_trade(trade_id):
    if not session.get("user_id"):
        return redirect(url_for("login"))

    trade = Trade.query.filter_by(id=trade_id, user_id=session["user_id"]).first_or_404()
    db.session.delete(trade)
    db.session.commit()
    return redirect(url_for("trades"))


@app.route("/imports/delete", methods=["POST"])
def delete_import_batch():
    if not session.get("user_id"):
        return redirect(url_for("login"))

    import_signature = request.form.get("import_signature", "").strip()
    if not import_signature:
        return redirect(
            url_for(
                "trades",
                batch_delete_status="error",
                batch_delete_message="Please select an import batch to delete.",
            )
        )

    deleted = (
        Trade.query.filter_by(
            user_id=session["user_id"],
            import_signature=import_signature,
        ).delete(synchronize_session=False)
    )
    db.session.commit()

    status = "success" if deleted > 0 else "info"
    message = (
        f"Deleted {deleted} trades for import signature {import_signature}."
        if deleted > 0
        else f"No trades found for import signature {import_signature}."
    )
    return redirect(
        url_for(
            "trades",
            batch_delete_status=status,
            batch_delete_message=message,
        )
    )

if __name__ == "__main__":
    debug_mode = os.getenv("FLASK_DEBUG", "0").strip().lower() in {"1", "true", "yes"}
    app.run(debug=debug_mode)
