import os
import re
from datetime import datetime, timedelta
from urllib.parse import parse_qsl, urlencode, urlparse, urlsplit, urlunsplit
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError
from dotenv import load_dotenv
from flask import Flask, g, jsonify, redirect, render_template, request, session, url_for
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from flask_migrate import Migrate
from flask_wtf.csrf import CSRFProtect
from sqlalchemy import func, or_
from sqlalchemy.exc import IntegrityError, OperationalError
from werkzeug.exceptions import HTTPException, RequestEntityTooLarge
from werkzeug.middleware.proxy_fix import ProxyFix
from werkzeug.security import check_password_hash, generate_password_hash
from auth_account import (
    build_external_url,
    generate_auth_token,
    is_admin_email,
    register_public_auth_routes,
    send_email_placeholder,
)
from ai_service import (
    AIConfigError,
    AIRequestError,
    get_latest_trade_week_period,
    get_weekly_dashboard_period,
    maybe_generate_weekly_dashboard_advice,
)
from models import (
    AIGeneratedResponse,
    Trade,
    TradeAccount,
    User,
    db,
    generate_trade_account_pubkey,
    generate_trade_pubkey,
)
from trading import (
    build_trade_analytics,
    build_dashboard_insight,
    build_import_signature,
    calc_pnl_values,
    canonicalize_symbol,
    derive_exit_price,
    format_trade_symbol,
    get_account_type_choices,
    get_timezone,
    get_trade_account_type,
    get_symbol_options,
    normalize_account_type,
    normalize_symbol,
    detect_trade_import_profile,
    parse_import_signature_datetime,
    parse_futures_contract_code,
    parse_tradovate_csv_stream,
    parse_mt5_xlsx_stream,
    resolve_pips,
    resolve_pnl,
    resolve_ticks,
    to_display_timezone,
)

load_dotenv()

TRUE_VALUES = {"1", "true", "yes", "on"}


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in TRUE_VALUES


def env_int(name, default):
    value = os.getenv(name)
    if value is None:
        return default
    try:
        return int(value.strip())
    except (TypeError, ValueError):
        return default


def get_app_timezone_name():
    return os.getenv("APP_TIMEZONE", "Asia/Singapore").strip() or "Asia/Singapore"


def normalize_timezone_name(value, default=None):
    text_value = str(value or "").strip()
    if not text_value:
        return default
    try:
        ZoneInfo(text_value)
    except ZoneInfoNotFoundError:
        return default
    return text_value


def get_display_timezone_name():
    return normalize_timezone_name(session.get("display_timezone"), get_app_timezone_name()) or "UTC"


def parse_local_datetime_input(raw_value):
    text_value = str(raw_value or "").strip()
    if not text_value:
        return None

    try:
        local_value = datetime.strptime(text_value, "%Y-%m-%dT%H:%M")
    except ValueError:
        try:
            local_value = datetime.strptime(text_value, "%Y-%m-%d")
        except ValueError:
            return None

    timezone_name = get_display_timezone_name()
    local_aware = local_value.replace(tzinfo=get_timezone(timezone_name))
    return local_aware.astimezone(get_timezone("UTC")).replace(tzinfo=None)


def format_local_datetime_input(value):
    local_value = to_display_timezone(value, get_display_timezone_name())
    if local_value is None:
        return ""
    return local_value.strftime("%Y-%m-%dT%H:%M")


def is_local_dev_environment():
    app_env = os.getenv("APP_ENV", "").strip().lower()
    flask_env = os.getenv("FLASK_ENV", "").strip().lower()
    return (
        env_bool("FLASK_DEBUG", False)
        or app_env in {"local", "development", "dev"}
        or flask_env in {"local", "development", "dev"}
    )

##Code was scaffolded by me, then heavily expanded and polished with the help of ChatGPT Codex. The overall architecture and ideas were done by me.
##HTML was generated by ChatGPT with some manual tweaks.
app = Flask(__name__)
if env_bool("TRUST_PROXY_HEADERS", default=not is_local_dev_environment()):
    app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1)
secret_key = os.getenv("SECRET_KEY")
if not secret_key:
    # Non-hardcoded fallback for local runs if .env is missing.
    secret_key = os.urandom(32).hex()
app.config["SECRET_KEY"] = secret_key
app.config["SESSION_COOKIE_HTTPONLY"] = True
app.config["SESSION_COOKIE_SAMESITE"] = "Lax"
session_cookie_secure_override = os.getenv("SESSION_COOKIE_SECURE")
if session_cookie_secure_override is None:
    # Safe default: secure cookies in deployed/server environments,
    # relaxed for explicit local/dev mode.
    session_cookie_secure = not is_local_dev_environment()
else:
    session_cookie_secure = env_bool("SESSION_COOKIE_SECURE", False)
app.config["SESSION_COOKIE_SECURE"] = session_cookie_secure
max_upload_mb = int(os.getenv("MAX_UPLOAD_MB", "4"))
app.config["MAX_CONTENT_LENGTH"] = max_upload_mb * 1024 * 1024

# Database URL placeholder flow:
# 1) Set DATABASE_URL in your environment for Postgres
# 2) If missing, fallback to local SQLite for development
database_url = os.getenv("DATABASE_URL", "sqlite:///FXJournal.db")
if database_url.startswith("postgres://"):
    database_url = database_url.replace("postgres://", "postgresql+psycopg://", 1)
elif database_url.startswith("postgresql://") and "+psycopg" not in database_url:
    database_url = database_url.replace("postgresql://", "postgresql+psycopg://", 1)

app.config["SQLALCHEMY_DATABASE_URI"] = database_url
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
db.init_app(app)
migrate = Migrate(app, db, directory="migrations", compare_type=True)
csrf = CSRFProtect(app)
# For production, set RATELIMIT_STORAGE_URI to Redis for shared counters.
limiter = Limiter(
    key_func=get_remote_address,
    default_limits=[],
    storage_uri=os.getenv("RATELIMIT_STORAGE_URI", "memory://"),
)
limiter.init_app(app)

TOKEN_PURPOSE_VERIFY_EMAIL = "verify_email"
TOKEN_PURPOSE_PASSWORD_RESET = "password_reset"
LEGAL_LAST_UPDATED = "March 8, 2026"
CONTACT_CATEGORY_CHOICES = (
    "Feedback",
    "Bug Report",
    "Privacy / Data Issue",
    "Account / Access Issue",
    "General Enquiry",
    "Other",
)
CONTACT_EMAIL_RE = re.compile(r"^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")


def get_trade_size_label(account_type):
    return "Contracts" if normalize_account_type(account_type) == "FUTURES" else "Lots"


def build_trade_duplicate_key(
    *,
    symbol,
    contract_code=None,
    side,
    entry_price,
    exit_price,
    lot_size,
    opened_at,
    closed_at,
    pnl,
):
    def quantize(value, digits=8):
        if value is None:
            return None
        return round(float(value), digits)

    return (
        normalize_symbol(contract_code or symbol),
        str(side or "").strip().upper(),
        quantize(entry_price),
        quantize(exit_price),
        quantize(lot_size),
        quantize(pnl, digits=2),
        opened_at.isoformat() if opened_at else None,
        closed_at.isoformat() if closed_at else None,
    )


def get_user_trade_accounts(user_id):
    return (
        TradeAccount.query.filter_by(user_id=user_id)
        .order_by(TradeAccount.is_default.desc(), TradeAccount.id.asc())
        .all()
    )


def ensure_trade_account_for_user(user_id):
    changed = False
    accounts = (
        TradeAccount.query.filter_by(user_id=user_id)
        .order_by(TradeAccount.id.asc())
        .all()
    )
    if not accounts:
        default_account = TradeAccount(
            user_id=user_id,
            name="Main Account",
            account_type="CFD",
            is_default=True,
        )
        db.session.add(default_account)
        db.session.flush()
        accounts = [default_account]
        changed = True

    if not any(account.is_default for account in accounts):
        accounts[0].is_default = True
        changed = True

    return accounts, changed


def ensure_trade_accounts_backfill():
    changed = False
    user_rows = db.session.query(User.id).all()

    for (user_id,) in user_rows:
        accounts, account_changed = ensure_trade_account_for_user(user_id)
        if account_changed:
            changed = True

        default_account = next((account for account in accounts if account.is_default), None)
        if default_account is None:
            default_account = accounts[0]

        linked = Trade.query.filter_by(user_id=user_id, trade_account_id=None).update(
            {"trade_account_id": default_account.id},
            synchronize_session=False,
        )
        if linked:
            changed = True

    if changed:
        db.session.commit()


def normalize_trade_account_name(value):
    return " ".join(str(value or "").strip().split())


def parse_trade_account_size(value):
    text_value = str(value or "").strip().replace(",", "")
    if not text_value:
        return None
    try:
        account_size = float(text_value)
    except (TypeError, ValueError) as exc:
        raise ValueError("invalid account size") from exc
    if account_size <= 0:
        raise ValueError("invalid account size")
    return account_size


def append_query_params(path_or_url, **params):
    parsed = urlsplit(str(path_or_url or ""))
    query_items = dict(parse_qsl(parsed.query, keep_blank_values=True))
    for key, value in params.items():
        if value is None:
            query_items.pop(key, None)
            continue
        text_value = str(value).strip()
        if not text_value:
            query_items.pop(key, None)
            continue
        query_items[key] = text_value
    return urlunsplit(
        (
            parsed.scheme,
            parsed.netloc,
            parsed.path,
            urlencode(query_items, doseq=True),
            parsed.fragment,
        )
    )


def get_safe_internal_next(default_endpoint):
    next_value = (
        request.form.get("next", "").strip()
        or request.args.get("next", "").strip()
        or request.referrer
        or ""
    )
    if next_value.startswith("/") and not next_value.startswith("//"):
        return next_value
    return url_for(default_endpoint)


def resolve_active_trade_account(user_id, requested_account_id=None, requested_account_pubkey=None):
    accounts, changed = ensure_trade_account_for_user(user_id)
    if changed:
        db.session.commit()
        accounts = get_user_trade_accounts(user_id)

    if requested_account_pubkey is not None:
        requested_pubkey = str(requested_account_pubkey).strip()
        if requested_pubkey:
            requested_match = next(
                (account for account in accounts if account.pubkey == requested_pubkey),
                None,
            )
            if requested_match:
                session["active_trade_account_id"] = requested_match.id
                return requested_match, accounts

    if requested_account_id is not None:
        try:
            requested_id = int(str(requested_account_id).strip())
        except (TypeError, ValueError):
            requested_id = None
        if requested_id is not None:
            requested_match = next(
                (account for account in accounts if account.id == requested_id),
                None,
            )
            if requested_match:
                session["active_trade_account_id"] = requested_match.id
                return requested_match, accounts

    try:
        active_id = int(str(session.get("active_trade_account_id", "")).strip())
    except (TypeError, ValueError):
        active_id = None
    active_account = next(
        (account for account in accounts if account.id == active_id),
        None,
    )
    if not active_account:
        active_account = next(
            (account for account in accounts if account.is_default),
            accounts[0],
        )
        session["active_trade_account_id"] = active_account.id
    return active_account, accounts


def get_active_trade_account_for_user(user_id):
    active_account = getattr(g, "active_trade_account", None)
    if active_account and active_account.user_id == user_id:
        return active_account
    active_account, _accounts = resolve_active_trade_account(user_id)
    return active_account


def get_user_trade_account_by_pubkey(user_id, trade_account_pubkey):
    return TradeAccount.query.filter_by(
        user_id=user_id,
        pubkey=str(trade_account_pubkey or "").strip(),
    ).first()


def get_user_trade_account_by_pubkey_or_404(user_id, trade_account_pubkey):
    return TradeAccount.query.filter_by(
        user_id=user_id,
        pubkey=str(trade_account_pubkey or "").strip(),
    ).first_or_404()


def get_user_trade_by_pubkey_or_404(user_id, trade_pubkey):
    return Trade.query.filter_by(
        user_id=user_id,
        pubkey=str(trade_pubkey or "").strip(),
    ).first_or_404()


def build_unique_trade_pubkey(reserved_pubkeys=None):
    reserved = reserved_pubkeys if reserved_pubkeys is not None else set()
    while True:
        candidate = generate_trade_pubkey()
        if candidate in reserved:
            continue
        exists = db.session.query(Trade.id).filter_by(pubkey=candidate).first()
        if exists:
            continue
        reserved.add(candidate)
        return candidate


def build_unique_trade_account_pubkey(reserved_pubkeys=None):
    reserved = reserved_pubkeys if reserved_pubkeys is not None else set()
    while True:
        candidate = generate_trade_account_pubkey()
        if candidate in reserved:
            continue
        exists = db.session.query(TradeAccount.id).filter_by(pubkey=candidate).first()
        if exists:
            continue
        reserved.add(candidate)
        return candidate


def delete_users_with_related_data(user_ids):
    normalized_ids = sorted({int(user_id) for user_id in user_ids if user_id is not None})
    if not normalized_ids:
        return 0

    AIGeneratedResponse.query.filter(AIGeneratedResponse.user_id.in_(normalized_ids)).delete(
        synchronize_session=False
    )
    Trade.query.filter(Trade.user_id.in_(normalized_ids)).delete(
        synchronize_session=False
    )
    TradeAccount.query.filter(TradeAccount.user_id.in_(normalized_ids)).delete(
        synchronize_session=False
    )
    return User.query.filter(User.id.in_(normalized_ids)).delete(
        synchronize_session=False
    )


def purge_expired_unverified_users():
    max_age_seconds = env_int("EMAIL_VERIFY_TOKEN_MAX_AGE_SECONDS", 86400)
    cutoff = datetime.utcnow() - timedelta(seconds=max_age_seconds)
    expired_user_ids = [
        user_id
        for user_id, in db.session.query(User.id).filter(
            User.email_verified.is_(False),
            User.verification_sent_at.isnot(None),
            User.verification_sent_at < cutoff,
        )
    ]
    if not expired_user_ids:
        return 0

    try:
        deleted_count = delete_users_with_related_data(expired_user_ids)
        db.session.commit()
        return deleted_count
    except (OperationalError, IntegrityError):
        db.session.rollback()
        app.logger.exception("Failed to purge expired unverified users.")
        return 0

def _is_same_origin(url_value):
    parsed = urlparse(url_value)
    if parsed.scheme not in {"http", "https"}:
        return False
    return parsed.netloc == request.host


@app.before_request
def cleanup_expired_unverified_accounts():
    purge_expired_unverified_users()

    pending_email = session.get("pending_verify_email", "").strip().lower()
    if pending_email and not User.query.filter_by(email=pending_email).first():
        session.pop("pending_verify_email", None)
    return None


@app.before_request
def load_display_timezone_context():
    g.display_timezone_name = get_display_timezone_name()
    return None


@app.before_request
def load_trade_account_context():
    g.active_trade_account = None
    g.user_trade_accounts = []
    user_id = session.get("user_id")
    if not user_id:
        return None

    active_account, accounts = resolve_active_trade_account(user_id)
    g.active_trade_account = active_account
    g.user_trade_accounts = accounts
    return None


@app.before_request
def enforce_same_origin_for_authenticated_posts():
    if request.method != "POST":
        return None
    if not session.get("user_id"):
        return None

    origin = request.headers.get("Origin", "").strip()
    referer = request.headers.get("Referer", "").strip()
    if origin and not _is_same_origin(origin):
        return "Forbidden", 403
    if not origin and referer and not _is_same_origin(referer):
        return "Forbidden", 403
    return None


@app.context_processor
def inject_trade_account_context():
    current_user = None
    user_id = session.get("user_id")
    if user_id:
        current_user = User.query.filter_by(id=user_id).first()
    return {
        "active_trade_account": getattr(g, "active_trade_account", None),
        "header_trade_accounts": getattr(g, "user_trade_accounts", []),
        "display_timezone_name": getattr(g, "display_timezone_name", get_app_timezone_name()),
        "is_admin_user": bool(current_user and is_admin_email(current_user.email)),
    }


@app.after_request
def set_security_headers(response):
    response.headers.setdefault("X-Content-Type-Options", "nosniff")
    response.headers.setdefault("X-Frame-Options", "SAMEORIGIN")
    response.headers.setdefault("Referrer-Policy", "strict-origin-when-cross-origin")
    return response


@app.route("/session/display-timezone", methods=["POST"])
def set_display_timezone():
    payload = request.get_json(silent=True) or {}
    timezone_name = normalize_timezone_name(
        payload.get("timezone") or request.form.get("timezone"),
        default=None,
    )
    if not timezone_name:
        return "", 400

    if session.get("display_timezone") != timezone_name:
        session["display_timezone"] = timezone_name
        session.modified = True
    return "", 204


@app.errorhandler(RequestEntityTooLarge)
def handle_large_upload(_error):
    if session.get("user_id"):
        return redirect(
            url_for(
                "new_trade",
                import_status="error",
                import_message=f"File too large. Max upload is {max_upload_mb} MB.",
            )
        )
    return redirect(url_for("login"))


@app.errorhandler(429)
def handle_rate_limit(_error):
    if request.path == "/login":
        success_message = request.args.get("success", "").strip()
        return (
            render_template(
                "login.html",
                title="Login | FX Journal",
                body_class="auth-layout",
                error="Too many login attempts. Please wait a minute and try again.",
                success=success_message or None,
            ),
            429,
        )
    return "Too many requests. Please try again later.", 429


def render_error_page(status_code, heading, description, title=None):
    user_logged_in = bool(session.get("user_id"))
    primary_endpoint = "home" if user_logged_in else "login"
    primary_label = "Back to Dashboard" if user_logged_in else "Go to Login"
    secondary_endpoint = "trades" if user_logged_in else None
    secondary_label = "View Trades" if user_logged_in else None
    return (
        render_template(
            "error.html",
            title=title or f"{status_code} | FX Journal",
            status_code=status_code,
            heading=heading,
            description=description,
            primary_url=url_for(primary_endpoint),
            primary_label=primary_label,
            secondary_url=url_for(secondary_endpoint) if secondary_endpoint else None,
            secondary_label=secondary_label,
            request_path=request.path,
        ),
        status_code,
    )


@app.errorhandler(HTTPException)
def handle_http_error(error):
    page_content = {
        403: (
            "Access denied",
            "You do not have permission to view this page.",
            "403 | FX Journal",
        ),
        404: (
            "Page not found",
            "The page you requested does not exist or may have moved.",
            "404 | FX Journal",
        ),
        405: (
            "Method not allowed",
            "That action is not available for this page.",
            "405 | FX Journal",
        ),
    }
    heading, description, title = page_content.get(
        error.code,
        (
            error.name or "Request error",
            error.description or "Something went wrong while processing your request.",
            f"{error.code} | FX Journal" if error.code else "Error | FX Journal",
        ),
    )
    return render_error_page(error.code or 500, heading, description, title=title)


@app.errorhandler(Exception)
def handle_unexpected_error(error):
    app.logger.exception("Unhandled application error.", exc_info=error)
    return render_error_page(
        500,
        "Something broke on our side",
        "The page could not be loaded right now. Please try again in a moment.",
        title="500 | FX Journal",
    )


register_public_auth_routes(
    app,
    limiter,
    legal_last_updated=LEGAL_LAST_UPDATED,
    token_purpose_verify_email=TOKEN_PURPOSE_VERIFY_EMAIL,
    token_purpose_password_reset=TOKEN_PURPOSE_PASSWORD_RESET,
    env_int=env_int,
    is_local_dev_environment=is_local_dev_environment,
    resolve_active_trade_account=resolve_active_trade_account,
)


@app.route("/dashboard")
def home():
    if not session.get("user_id"):
        return redirect(url_for("login"))

    username = session.get("username", "User")
    user_id = session["user_id"]
    active_trade_account = get_active_trade_account_for_user(user_id)

    try:
        user_trades = (
            Trade.query.filter_by(
                user_id=user_id,
                trade_account_id=active_trade_account.id,
            )
            .order_by(Trade.opened_at.desc())
            .all()
        )
    except OperationalError:
        db.session.rollback()
        user_trades = []

    timezone_name = get_display_timezone_name()
    analytics = build_trade_analytics(
        user_trades,
        display_timezone_name=timezone_name,
        account_size=active_trade_account.account_size if active_trade_account else None,
    )
    summary = analytics["summary"]
    closed = [(record["trade"], record["pnl"]) for record in analytics["closed_records"]]
    now_local = to_display_timezone(datetime.utcnow(), timezone_name)
    trades_this_month = sum(
        1
        for trade in user_trades
        if (opened_local := to_display_timezone(trade.opened_at, timezone_name))
        and opened_local.month == now_local.month
        and opened_local.year == now_local.year
    )

    recent_trades = []
    size_label = get_trade_size_label(active_trade_account.account_type)
    for trade in user_trades:
        pnl_value = resolve_pnl(trade)
        pips_value = resolve_pips(trade)
        ticks_value = resolve_ticks(trade)
        opened_local = to_display_timezone(trade.opened_at, timezone_name)
        trade_date = opened_local.strftime("%d %b %Y") if opened_local else "-"
        trade_date_value = opened_local.strftime("%Y-%m-%d") if opened_local else ""
        recent_trades.append(
            {
                "symbol": format_trade_symbol(trade),
                "side": trade.side,
                "entry_price": trade.entry_price,
                "exit_price": trade.exit_price,
                "lot_size": trade.lot_size,
                "pnl": pnl_value,
                "pips": pips_value,
                "ticks": ticks_value,
                "date": trade_date,
                "date_value": trade_date_value,
                "status": "Closed" if trade.exit_price is not None else "Running",
            }
        )

    chart_points = analytics["daily_equity_curve"]
    dashboard_insight = build_dashboard_insight(user_trades, closed)
    weekly_ai_review = None
    weekly_ai_generated_at_label = ""
    weekly_ai_period_label = ""
    weekly_ai_empty_message = (
        "Your weekly AI review appears once this account has an eligible trade week. It uses the most recent eligible week with trades for the active account."
    )

    try:
        weekly_ai_result = maybe_generate_weekly_dashboard_advice(
            user_id=user_id,
            trade_account_id=active_trade_account.id if active_trade_account else None,
            prompt_filename="dashboard_advice.txt",
        )
        weekly_ai_review = weekly_ai_result.get("record")
        weekly_period = weekly_ai_result.get("period") or get_latest_trade_week_period(
            user_id=user_id,
            trade_account_id=active_trade_account.id if active_trade_account else None,
        )
    except (AIConfigError, AIRequestError, OSError, ValueError) as exc:
        db.session.rollback()
        app.logger.warning("Weekly AI review unavailable: %s", exc)
        weekly_period = get_latest_trade_week_period(
            user_id=user_id,
            trade_account_id=active_trade_account.id if active_trade_account else None,
        ) or get_weekly_dashboard_period()
        weekly_ai_empty_message = "Weekly AI review is temporarily unavailable."

    if weekly_ai_review and weekly_ai_review.generated_at:
        generated_local = to_display_timezone(weekly_ai_review.generated_at, timezone_name)
        if generated_local is not None:
            weekly_ai_generated_at_label = generated_local.strftime("%d %b %Y %H:%M")

    period_end_local = to_display_timezone(
        weekly_period.get("period_end_utc") if weekly_period else None,
        timezone_name,
    )
    if period_end_local is not None:
        weekly_ai_period_label = (
            f"{period_end_local.strftime('%a %d %b %Y %H:%M')} {timezone_name}"
        )

    return render_template(
        "index.html",
        title="FX Journal",
        username=username,
        win_rate=summary["win_rate"],
        net_pnl_week=summary["weekly_pnl"],
        account_pnl_total=summary["net_pnl"],
        trades_this_month=trades_this_month,
        avg_rr_display=summary["risk_reward_display"],
        avg_rr_known=summary["risk_reward_known"],
        avg_rr_mode=summary["risk_reward_mode"],
        recent_trades=recent_trades,
        size_label=size_label,
        chart_points=chart_points,
        dashboard_insight=dashboard_insight,
        weekly_ai_review=weekly_ai_review,
        weekly_ai_generated_at_label=weekly_ai_generated_at_label,
        weekly_ai_period_label=weekly_ai_period_label,
        weekly_ai_empty_message=weekly_ai_empty_message,
    )


@app.route("/dashboard/analytics")
def analytics():
    if not session.get("user_id"):
        return redirect(url_for("login"))

    user_id = session["user_id"]
    active_trade_account = get_active_trade_account_for_user(user_id)
    timezone_name = get_display_timezone_name()

    try:
        user_trades = (
            Trade.query.filter_by(
                user_id=user_id,
                trade_account_id=active_trade_account.id,
            )
            .order_by(Trade.opened_at.desc())
            .all()
        )
    except OperationalError:
        db.session.rollback()
        user_trades = []

    analytics_payload = build_trade_analytics(
        user_trades,
        display_timezone_name=timezone_name,
        account_size=active_trade_account.account_size if active_trade_account else None,
    )

    return render_template(
        "analytics.html",
        title="Analytics | FX Journal",
        username=session.get("username", "User"),
        analytics=analytics_payload,
        analytics_timezone=timezone_name,
        active_trade_account=active_trade_account,
    )


@app.route("/account", methods=["GET", "POST"])
def account():
    if not session.get("user_id"):
        return redirect(url_for("login"))

    user = User.query.filter_by(id=session["user_id"]).first_or_404()

    if request.method == "POST":
        username = request.form.get("username", "").strip()
        email = request.form.get("email", "").strip().lower()

        if not username or not email:
            return redirect(
                url_for(
                    "account",
                    account_status="error",
                    account_message="Username and email are required.",
                )
            )

        conflicting_user = User.query.filter(
            User.id != user.id,
            or_(User.username == username, User.email == email),
        ).first()
        if conflicting_user:
            return redirect(
                url_for(
                    "account",
                    account_status="error",
                    account_message="Username or email is already in use.",
                )
            )

        username_changed = user.username != username
        user.username = username
        user.email = email

        try:
            db.session.commit()
        except OperationalError:
            db.session.rollback()
            return redirect(
                url_for(
                    "account",
                    account_status="error",
                    account_message="Could not save account changes. Please try again.",
                )
            )

        if username_changed:
            session["username"] = username

        return redirect(
            url_for(
                "account",
                account_status="success",
                account_message="Account details updated.",
            )
        )

    account_status = request.args.get("account_status", "").strip().lower()
    account_message = request.args.get("account_message", "").strip()
    debug_reset_link = request.args.get("debug_reset_link", "").strip()
    if not (
        debug_reset_link.startswith("http://")
        or debug_reset_link.startswith("https://")
    ):
        debug_reset_link = ""
    if account_status not in {"success", "error", "info"}:
        account_status = ""
    if not account_message:
        account_status = ""

    total_trades = Trade.query.filter_by(user_id=user.id).count()
    closed_trades = (
        Trade.query.filter_by(user_id=user.id)
        .filter(Trade.exit_price.isnot(None))
        .count()
    )
    imported_trades = (
        Trade.query.filter_by(user_id=user.id)
        .filter(Trade.import_signature.isnot(None))
        .count()
    )

    return render_template(
        "account.html",
        title="My Account | FX Journal",
        username=session.get("username", "User"),
        account_user=user,
        email_verified=bool(user.email_verified),
        account_status=account_status,
        account_message=account_message,
        total_trades=total_trades,
        closed_trades=closed_trades,
        running_trades=max(total_trades - closed_trades, 0),
        imported_trades=imported_trades,
        debug_reset_link=debug_reset_link or None,
        user_trade_accounts=getattr(g, "user_trade_accounts", []),
        active_trade_account=getattr(g, "active_trade_account", None),
    )


@app.route("/account/password-reset-email", methods=["POST"])
@limiter.limit(
    "5 per minute;20 per hour",
    methods=["POST"],
    error_message="Too many attempts. Please wait and try again.",
)
def account_password_reset_email():
    if not session.get("user_id"):
        return redirect(url_for("login"))

    user = User.query.filter_by(id=session["user_id"]).first_or_404()
    reset_token = generate_auth_token(
        email=user.email,
        purpose=TOKEN_PURPOSE_PASSWORD_RESET,
    )
    reset_link = build_external_url(url_for("reset_password_token", token=reset_token))
    email_subject = "Reset your FX Journal password"
    email_body = (
        f"Hi {user.username},\n\n"
        "You requested a password reset.\n"
        "Open this link to set a new password:\n"
        f"{reset_link}\n\n"
        "If you did not request this, you can ignore this email."
    )
    email_result = send_email_placeholder(user.email, email_subject, email_body)

    kwargs = {
        "account_status": "info",
        "account_message": "If email sending is configured, a password reset link was sent to your account email.",
    }
    if is_local_dev_environment() and not email_result.get("sent"):
        kwargs["debug_reset_link"] = reset_link
    return redirect(url_for("account", **kwargs))


@app.route("/account/delete", methods=["POST"])
@limiter.limit(
    "2 per hour",
    methods=["POST"],
    error_message="Too many account deletion attempts. Please wait and try again.",
)
def delete_account():
    if not session.get("user_id"):
        return redirect(url_for("login"))

    user = User.query.filter_by(id=session["user_id"]).first()
    if not user:
        session.clear()
        return redirect(url_for("login"))

    confirmation_text = request.form.get("delete_confirmation", "").strip().upper()
    acknowledged = request.form.get("delete_acknowledge") == "on"
    if confirmation_text != "DELETE" or not acknowledged:
        return redirect(
            url_for(
                "account",
                account_status="error",
                account_message=(
                    "To delete your account, type DELETE and tick the confirmation checkbox."
                ),
            )
        )

    try:
        delete_users_with_related_data([user.id])
        db.session.commit()
    except (OperationalError, IntegrityError):
        db.session.rollback()
        return redirect(
            url_for(
                "account",
                account_status="error",
                account_message="Could not delete account right now. Please try again.",
            )
        )

    session.clear()
    return redirect(
        url_for(
            "login",
            success="Your account and all related trade, account, and AI review data were deleted.",
        )
    )


@app.route("/dashboard/trade-accounts/switch", methods=["POST"])
def switch_trade_account():
    if not session.get("user_id"):
        return redirect(url_for("login"))

    requested_account_id = request.form.get("trade_account_id", "").strip()
    requested_account_pubkey = request.form.get("trade_account_pubkey", "").strip()
    _active, _accounts = resolve_active_trade_account(
        session["user_id"],
        requested_account_id=requested_account_id,
        requested_account_pubkey=requested_account_pubkey,
    )
    next_path = request.form.get("next", "").strip()
    if next_path.startswith("/") and not next_path.startswith("//"):
        return redirect(next_path)
    return redirect(request.referrer or url_for("home"))


@app.route("/dashboard/trade-accounts", methods=["POST"])
@limiter.limit(
    "6 per minute;30 per hour",
    methods=["POST"],
    error_message="Too many trade account actions. Please wait and try again.",
)
def create_trade_account():
    if not session.get("user_id"):
        return redirect(url_for("login"))

    user_id = session["user_id"]
    account_name = normalize_trade_account_name(request.form.get("trade_account_name"))
    account_type = normalize_account_type(request.form.get("account_type"))
    external_account_id = normalize_trade_account_name(
        request.form.get("external_account_id")
    )
    try:
        account_size = parse_trade_account_size(request.form.get("account_size"))
    except ValueError:
        return redirect(
            append_query_params(
                get_safe_internal_next("trade_accounts"),
                trade_account_status="error",
                trade_account_message="Account size must be a positive number or left blank.",
            )
        )

    if not account_name:
        return redirect(
            append_query_params(
                get_safe_internal_next("trade_accounts"),
                trade_account_status="error",
                trade_account_message="Trade account name is required.",
            )
        )
    if len(account_name) > 80:
        return redirect(
            append_query_params(
                get_safe_internal_next("trade_accounts"),
                trade_account_status="error",
                trade_account_message="Trade account name must be 80 characters or less.",
            )
        )
    if external_account_id and len(external_account_id) > 80:
        return redirect(
            append_query_params(
                get_safe_internal_next("trade_accounts"),
                trade_account_status="error",
                trade_account_message="External account ID must be 80 characters or less.",
            )
        )

    existing_accounts = get_user_trade_accounts(user_id)
    lowered_name = account_name.lower()
    if any(normalize_trade_account_name(account.name).lower() == lowered_name for account in existing_accounts):
        return redirect(
            append_query_params(
                get_safe_internal_next("trade_accounts"),
                trade_account_status="error",
                trade_account_message="A trade account with that name already exists.",
            )
        )

    lowered_external = external_account_id.lower()
    if external_account_id and any(
        normalize_trade_account_name(account.external_account_id).lower() == lowered_external
        for account in existing_accounts
        if account.external_account_id
    ):
        return redirect(
            append_query_params(
                get_safe_internal_next("trade_accounts"),
                trade_account_status="error",
                trade_account_message="That external account ID is already linked.",
            )
        )

    wants_default = request.form.get("set_as_default", "").strip().lower() in TRUE_VALUES
    is_default = wants_default or not existing_accounts
    if is_default:
        for account in existing_accounts:
            account.is_default = False

    new_account = TradeAccount(
        pubkey=build_unique_trade_account_pubkey(),
        user_id=user_id,
        name=account_name,
        external_account_id=external_account_id or None,
        account_size=account_size,
        account_type=account_type,
        is_default=is_default,
    )
    db.session.add(new_account)
    db.session.commit()

    session["active_trade_account_id"] = new_account.id
    return redirect(
        append_query_params(
            get_safe_internal_next("trade_accounts"),
            trade_account_status="success",
            trade_account_message=f"Trade account '{new_account.name}' added.",
        )
    )


@app.route("/dashboard/trade-accounts/<string:trade_account_pubkey>/default", methods=["POST"])
def set_default_trade_account(trade_account_pubkey):
    if not session.get("user_id"):
        return redirect(url_for("login"))

    user_id = session["user_id"]
    selected = get_user_trade_account_by_pubkey(user_id, trade_account_pubkey)
    if not selected:
        return redirect(
            append_query_params(
                get_safe_internal_next("trade_accounts"),
                trade_account_status="error",
                trade_account_message="Trade account not found.",
            )
        )

    TradeAccount.query.filter_by(user_id=user_id).update(
        {"is_default": False},
        synchronize_session=False,
    )
    selected.is_default = True
    db.session.commit()
    session["active_trade_account_id"] = selected.id

    return redirect(
        append_query_params(
            get_safe_internal_next("trade_accounts"),
            trade_account_status="info",
            trade_account_message=f"Default trade account set to '{selected.name}'.",
        )
    )


@app.route("/dashboard/trade-accounts/<string:trade_account_pubkey>/update", methods=["POST"])
def update_trade_account(trade_account_pubkey):
    if not session.get("user_id"):
        return redirect(url_for("login"))

    user_id = session["user_id"]
    account = get_user_trade_account_by_pubkey(user_id, trade_account_pubkey)
    if not account:
        return redirect(
            append_query_params(
                get_safe_internal_next("trade_accounts"),
                trade_account_status="error",
                trade_account_message="Trade account not found.",
            )
        )

    account_name = normalize_trade_account_name(request.form.get("trade_account_name"))
    account_type = normalize_account_type(request.form.get("account_type"))
    external_account_id = normalize_trade_account_name(
        request.form.get("external_account_id")
    )
    try:
        account_size = parse_trade_account_size(request.form.get("account_size"))
    except ValueError:
        return redirect(
            append_query_params(
                get_safe_internal_next("trade_accounts"),
                trade_account_status="error",
                trade_account_message="Account size must be a positive number or left blank.",
            )
        )

    if not account_name:
        return redirect(
            append_query_params(
                get_safe_internal_next("trade_accounts"),
                trade_account_status="error",
                trade_account_message="Trade account name is required.",
            )
        )
    if len(account_name) > 80:
        return redirect(
            append_query_params(
                get_safe_internal_next("trade_accounts"),
                trade_account_status="error",
                trade_account_message="Trade account name must be 80 characters or less.",
            )
        )
    if external_account_id and len(external_account_id) > 80:
        return redirect(
            append_query_params(
                get_safe_internal_next("trade_accounts"),
                trade_account_status="error",
                trade_account_message="External account ID must be 80 characters or less.",
            )
        )

    existing_accounts = get_user_trade_accounts(user_id)
    lowered_name = account_name.lower()
    for existing in existing_accounts:
        if existing.id == account.id:
            continue
        if normalize_trade_account_name(existing.name).lower() == lowered_name:
            return redirect(
                append_query_params(
                    get_safe_internal_next("trade_accounts"),
                    trade_account_status="error",
                    trade_account_message="A trade account with that name already exists.",
                )
            )

    lowered_external = external_account_id.lower()
    if external_account_id:
        for existing in existing_accounts:
            if existing.id == account.id or not existing.external_account_id:
                continue
            if normalize_trade_account_name(existing.external_account_id).lower() == lowered_external:
                return redirect(
                    append_query_params(
                        get_safe_internal_next("trade_accounts"),
                        trade_account_status="error",
                        trade_account_message="That external account ID is already linked.",
                    )
                )

    account.name = account_name
    account.external_account_id = external_account_id or None
    account.account_size = account_size
    account.account_type = account_type
    db.session.commit()
    return redirect(
        append_query_params(
            get_safe_internal_next("trade_accounts"),
            trade_account_status="success",
            trade_account_message=f"Trade account '{account.name}' updated.",
        )
    )


@app.route("/dashboard/trade-accounts/<string:trade_account_pubkey>/delete", methods=["POST"])
@limiter.limit(
    "3 per minute;10 per hour",
    methods=["POST"],
    error_message="Too many trade account deletion attempts. Please wait and try again.",
)
def delete_trade_account(trade_account_pubkey):
    wants_json_response = request.headers.get("X-Requested-With") == "XMLHttpRequest"

    def build_redirect_url(status, message):
        return append_query_params(
            get_safe_internal_next("trade_accounts"),
            trade_account_status=status,
            trade_account_message=message,
        )

    def respond_with_status(status, message, status_code=400):
        redirect_url = build_redirect_url(status, message)
        if wants_json_response:
            payload = {
                "ok": status == "success",
                "message": message,
                "redirect_url": redirect_url,
            }
            return jsonify(payload), status_code
        return redirect(redirect_url)

    if not session.get("user_id"):
        if wants_json_response:
            return jsonify(
                {
                    "ok": False,
                    "message": "Your session expired. Please sign in again.",
                    "redirect_url": url_for("login"),
                }
            ), 401
        return redirect(url_for("login"))

    user_id = session["user_id"]
    account = get_user_trade_account_by_pubkey(user_id, trade_account_pubkey)
    if not account:
        return respond_with_status("error", "Trade account not found.", 404)

    account_rows = get_user_trade_accounts(user_id)
    remaining_accounts = [row for row in account_rows if row.id != account.id]
    deleted_name = account.name
    deleted_trade_count = Trade.query.filter_by(
        user_id=user_id,
        trade_account_id=account.id,
    ).count()
    deleted_ai_review_count = AIGeneratedResponse.query.filter_by(
        user_id=user_id,
        trade_account_id=account.id,
    ).count()
    active_trade_account_id = session.get("active_trade_account_id")
    confirmation_text = request.form.get("delete_trade_account_confirmation", "").strip().upper()
    acknowledged = request.form.get("delete_trade_account_acknowledge") == "on"
    if confirmation_text != "DELETE" or not acknowledged:
        return respond_with_status(
            "error",
            f"To delete '{account.name}', type DELETE and tick the confirmation checkbox.",
        )

    try:
        next_active_account = None
        if remaining_accounts:
            if account.is_default:
                for row in remaining_accounts:
                    row.is_default = False
                remaining_accounts[0].is_default = True
            next_active_account = next(
                (row for row in remaining_accounts if row.id == active_trade_account_id),
                None,
            ) or next(
                (row for row in remaining_accounts if row.is_default),
                remaining_accounts[0],
            )

        db.session.delete(account)

        replacement_created = False
        if not remaining_accounts:
            next_active_account = TradeAccount(
                pubkey=build_unique_trade_account_pubkey(),
                user_id=user_id,
                name="Main Account",
                account_type="CFD",
                is_default=True,
            )
            db.session.add(next_active_account)
            db.session.flush()
            replacement_created = True

        db.session.commit()
    except (OperationalError, IntegrityError):
        db.session.rollback()
        return respond_with_status(
            "error",
            "Could not delete that trade account right now. Please try again.",
            500,
        )

    if next_active_account is not None:
        session["active_trade_account_id"] = next_active_account.id
    else:
        session.pop("active_trade_account_id", None)

    review_msg = (
        f" and {deleted_ai_review_count} linked AI review"
        f"{'' if deleted_ai_review_count == 1 else 's'}"
        if deleted_ai_review_count
        else ""
    )
    replacement_msg = " A fresh Main Account was created." if replacement_created else ""
    success_message = (
        f"Deleted trade account '{deleted_name}', {deleted_trade_count} linked trade"
        f"{'' if deleted_trade_count == 1 else 's'}{review_msg}."
        f"{replacement_msg}"
    )
    if wants_json_response:
        default_trade_account = next_active_account if replacement_created else next(
            (row for row in remaining_accounts if row.is_default),
            None,
        )
        redirect_url = build_redirect_url("success", success_message)
        return jsonify(
            {
                "ok": True,
                "message": success_message,
                "redirect_url": redirect_url,
                "deleted_pubkey": trade_account_pubkey,
                "remaining_account_count": len(remaining_accounts) + (1 if replacement_created else 0),
                "active_trade_account_pubkey": next_active_account.pubkey if next_active_account else None,
                "default_trade_account_pubkey": default_trade_account.pubkey if default_trade_account else None,
                "replacement_created": replacement_created,
                "requires_reload": replacement_created,
            }
        )
    return redirect(build_redirect_url("success", success_message))


@app.route("/dashboard/trade-accounts/delete-all", methods=["POST"])
@limiter.limit(
    "2 per hour",
    methods=["POST"],
    error_message="Too many destructive account actions. Please wait and try again.",
)
def delete_all_trade_accounts():
    if not session.get("user_id"):
        return redirect(url_for("login"))

    user_id = session["user_id"]
    confirmation_text = request.form.get("delete_all_trade_accounts_confirmation", "").strip().upper()
    acknowledged = request.form.get("delete_all_trade_accounts_acknowledge") == "on"
    if confirmation_text != "DELETE" or not acknowledged:
        return redirect(
            append_query_params(
                get_safe_internal_next("trade_accounts"),
                trade_account_status="error",
                trade_account_message="Type DELETE and tick the confirmation checkbox to remove every trade account.",
            )
        )

    trade_count = Trade.query.filter_by(user_id=user_id).count()
    account_count = TradeAccount.query.filter_by(user_id=user_id).count()
    ai_review_count = AIGeneratedResponse.query.filter_by(user_id=user_id).count()
    try:
        AIGeneratedResponse.query.filter_by(user_id=user_id).delete(synchronize_session=False)
        Trade.query.filter_by(user_id=user_id).delete(synchronize_session=False)
        TradeAccount.query.filter_by(user_id=user_id).delete(synchronize_session=False)

        replacement_account = TradeAccount(
            pubkey=build_unique_trade_account_pubkey(),
            user_id=user_id,
            name="Main Account",
            account_type="CFD",
            is_default=True,
        )
        db.session.add(replacement_account)
        db.session.commit()
    except (OperationalError, IntegrityError):
        db.session.rollback()
        return redirect(
            append_query_params(
                get_safe_internal_next("trade_accounts"),
                trade_account_status="error",
                trade_account_message="Could not delete every trade account right now. Please try again.",
            )
        )

    session["active_trade_account_id"] = replacement_account.id

    return redirect(
        append_query_params(
            get_safe_internal_next("trade_accounts"),
            trade_account_status="success",
            trade_account_message=(
                f"Deleted {account_count} trade accounts, {trade_count} linked trades, and "
                f"{ai_review_count} linked AI review{'s' if ai_review_count != 1 else ''}. "
                "A fresh Main Account was created."
            ),
        )
    )


@app.route("/contact", methods=["GET", "POST"])
@limiter.limit(
    "3 per minute;20 per day",
    methods=["POST"],
    error_message="Too many contact submissions. Please wait and try again later.",
)
def contact():
    user = None
    if session.get("user_id"):
        user = User.query.filter_by(id=session["user_id"]).first()

    contact_subject = ""
    contact_category = CONTACT_CATEGORY_CHOICES[0]
    contact_body = ""
    contact_email = user.email if user else ""

    def render_contact(status="", message="", code=200):
        return (
            render_template(
                "contact.html",
                title="Contact | FX Journal",
                username=session.get("username", "User"),
                contact_status=status,
                contact_message=message,
                contact_subject=contact_subject,
                contact_category=contact_category,
                contact_body=contact_body,
                contact_email=contact_email,
                contact_category_choices=CONTACT_CATEGORY_CHOICES,
                account_user=user,
            ),
            code,
        )

    if request.method == "POST":
        contact_subject = request.form.get("subject", "").strip()
        contact_category = request.form.get("category", "").strip()
        contact_body = request.form.get("message", "").strip()
        contact_email = (request.form.get("contact_email", "").strip().lower() if not user else user.email)

        if contact_category not in CONTACT_CATEGORY_CHOICES:
            return render_contact(
                "error",
                "Please choose a valid contact category.",
                400,
            )

        if not contact_subject or not contact_body or (not user and not contact_email):
            return render_contact(
                "error",
                "Email, subject, and message are required." if not user else "Subject and message are required.",
                400,
            )

        if len(contact_subject) > 120:
            return render_contact(
                "error",
                "Subject must be 120 characters or less.",
                400,
            )

        if len(contact_body) > 5000:
            return render_contact(
                "error",
                "Message must be 5000 characters or less.",
                400,
            )

        if not user and (
            len(contact_email) > 120 or not CONTACT_EMAIL_RE.match(contact_email)
        ):
            return render_contact(
                "error",
                "Enter a valid contact email address.",
                400,
            )

        contact_to_email = os.getenv("FEEDBACK_TO_EMAIL", "").strip().lower()
        if not contact_to_email:
            app.logger.warning(
                "Contact submit blocked: FEEDBACK_TO_EMAIL is not configured."
            )
            return render_contact(
                "error",
                "Contact email destination is not configured yet.",
                500,
            )

        submitted_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        requester_ip = (
            request.headers.get("X-Forwarded-For", "").split(",")[0].strip()
            or request.remote_addr
            or "-"
        )
        submitted_user_id = request.form.get("contact_user_id", "").strip()
        submitted_user_email = request.form.get("contact_user_email", "").strip().lower()
        if user:
            actor_name = user.username
            actor_user_id = str(user.id)
            actor_email = user.email
            actor_kind = "authenticated"
        else:
            actor_name = "Guest"
            actor_user_id = submitted_user_id or "-"
            actor_email = contact_email
            actor_kind = "guest"
        email_subject = f"[FX Journal Contact] [{contact_category}] {contact_subject}"
        email_body = (
            "New contact submission\n\n"
            f"Submitted at: {submitted_at}\n"
            f"Contact type: {actor_kind}\n"
            f"Name: {actor_name}\n"
            f"User ID: {actor_user_id}\n"
            f"Contact email: {actor_email}\n"
            f"Submitted hidden user email: {submitted_user_email or '-'}\n"
            f"Client IP: {requester_ip}\n"
            f"Category: {contact_category}\n"
            f"Subject: {contact_subject}\n\n"
            "Message:\n"
            f"{contact_body}\n"
        )
        email_result = send_email_placeholder(
            contact_to_email,
            email_subject,
            email_body,
        )

        if email_result.get("sent"):
            return redirect(
                url_for(
                    "contact",
                    contact_status="success",
                    contact_message="Message sent. I will review it as soon as possible.",
                )
            )

        if is_local_dev_environment():
            return redirect(
                url_for(
                    "contact",
                    contact_status="info",
                    contact_message=(
                        "Message captured in server logs. Email delivery is disabled in this environment."
                    ),
                )
            )

        return redirect(
            url_for(
                "contact",
                contact_status="info",
                contact_message="Message received, but email delivery is currently unavailable.",
            )
        )

    contact_status = (
        request.args.get("contact_status", "").strip().lower()
    )
    contact_message = (
        request.args.get("contact_message", "").strip()
    )
    if contact_status not in {"success", "error", "info"}:
        contact_status = ""
    if not contact_message:
        contact_status = ""

    return render_template(
        "contact.html",
        title="Contact | FX Journal",
        username=session.get("username", "User"),
        contact_status=contact_status,
        contact_message=contact_message,
        contact_subject=contact_subject,
        contact_category=contact_category,
        contact_body=contact_body,
        contact_email=contact_email,
        contact_category_choices=CONTACT_CATEGORY_CHOICES,
        account_user=user,
    )

@app.route("/dashboard/trades")
def trades():
    if not session.get("user_id"):
        return redirect(url_for("login"))

    username = session.get("username", "User")
    user_id = session["user_id"]
    active_trade_account = get_active_trade_account_for_user(user_id)
    try:
        user_trades = (
            Trade.query.filter_by(
                user_id=user_id,
                trade_account_id=active_trade_account.id,
            )
            .order_by(Trade.opened_at.desc())
            .all()
        )
    except OperationalError:
        db.session.rollback()
        user_trades = []

    trade_rows = []
    size_label = get_trade_size_label(active_trade_account.account_type)
    for trade in user_trades:
        trade_rows.append(
            {
                "id": trade.id,
                "pubkey": trade.pubkey,
                "symbol": format_trade_symbol(trade),
                "side": trade.side,
                "entry_price": trade.entry_price,
                "exit_price": trade.exit_price,
                "lot_size": trade.lot_size,
                "pnl": resolve_pnl(trade),
                "pips": resolve_pips(trade),
                "ticks": resolve_ticks(trade),
                "opened_at": trade.opened_at,
            }
        )

    batch_delete_status = request.args.get("batch_delete_status", "").strip().lower()
    batch_delete_message = request.args.get("batch_delete_message", "").strip()
    manage_mode = request.args.get("manage", "").strip().lower() in {"1", "true", "yes", "on"}
    trade_account_status = request.args.get("trade_account_status", "").strip().lower()
    trade_account_message = request.args.get("trade_account_message", "").strip()
    if batch_delete_status not in {"success", "error", "info"}:
        batch_delete_status = ""
    if not batch_delete_message:
        batch_delete_status = ""
    if trade_account_status not in {"success", "error", "info"}:
        trade_account_status = ""
    if not trade_account_message:
        trade_account_status = ""

    import_batch_map = {}
    for trade in user_trades:
        signature = (trade.import_signature or "").strip()
        if not signature:
            continue
        if signature not in import_batch_map:
            imported_at = parse_import_signature_datetime(signature)
            import_batch_map[signature] = {
                "signature": signature,
                "trade_count": 0,
                "imported_at": imported_at,
                "imported_at_label": (
                    imported_at.strftime("%Y-%m-%d %H:%M UTC")
                    if imported_at
                    else "Unknown import time"
                ),
            }
        import_batch_map[signature]["trade_count"] += 1

    import_batches = sorted(
        import_batch_map.values(),
        key=lambda batch: batch["imported_at"] or datetime.min,
        reverse=True,
    )

    return render_template(
        "trades.html",
        title="My Trades | FX Journal",
        username=username,
        trades=trade_rows,
        size_label=size_label,
        import_batches=import_batches,
        manage_mode=manage_mode,
        batch_delete_status=batch_delete_status,
        batch_delete_message=batch_delete_message,
        trade_account_status=trade_account_status,
        trade_account_message=trade_account_message,
    )


@app.route("/dashboard/trades/bulk-delete", methods=["POST"])
@limiter.limit(
    "6 per minute",
    methods=["POST"],
    error_message="Too many trade deletion attempts. Please wait and try again.",
)
def bulk_delete_trades():
    if not session.get("user_id"):
        return redirect(url_for("login"))

    user_id = session["user_id"]
    active_trade_account = get_active_trade_account_for_user(user_id)
    selected_pubkeys = [
        value.strip()
        for value in request.form.getlist("trade_pubkeys")
        if value and value.strip()
    ]

    if not selected_pubkeys:
        return redirect(
            url_for(
                "trades",
                manage="1",
                batch_delete_status="error",
                batch_delete_message="Select at least one trade to delete.",
            )
        )

    try:
        deleted = (
            Trade.query.filter(
                Trade.user_id == user_id,
                Trade.trade_account_id == active_trade_account.id,
                Trade.pubkey.in_(selected_pubkeys),
            ).delete(synchronize_session=False)
        )
        db.session.commit()
    except (OperationalError, IntegrityError):
        db.session.rollback()
        return redirect(
            url_for(
                "trades",
                manage="1",
                batch_delete_status="error",
                batch_delete_message="Could not delete the selected trades right now. Please try again.",
            )
        )

    status = "success" if deleted > 0 else "info"
    message = (
        f"Deleted {deleted} selected trade{'s' if deleted != 1 else ''}."
        if deleted > 0
        else "No trades matched the selected rows."
    )
    return redirect(
        url_for(
            "trades",
            manage="1",
            batch_delete_status=status,
            batch_delete_message=message,
        )
    )


@app.route("/dashboard/trade-accounts")
def trade_accounts():
    if not session.get("user_id"):
        return redirect(url_for("login"))

    user_id = session["user_id"]
    active_trade_account = get_active_trade_account_for_user(user_id)
    account_rows = get_user_trade_accounts(user_id)
    account_trade_counts = dict(
        db.session.query(Trade.trade_account_id, func.count(Trade.id))
        .filter_by(user_id=user_id)
        .group_by(Trade.trade_account_id)
        .all()
    )
    account_review_counts = dict(
        db.session.query(AIGeneratedResponse.trade_account_id, func.count(AIGeneratedResponse.id))
        .filter_by(user_id=user_id)
        .group_by(AIGeneratedResponse.trade_account_id)
        .all()
    )
    edit_pubkey = request.args.get("edit", "").strip() or request.args.get("edit_id", "").strip()
    delete_pubkey = request.args.get("delete", "").strip() or request.args.get("delete_id", "").strip()
    edit_target = None
    delete_target = None
    delete_target_trade_count = 0
    delete_target_ai_review_count = 0
    if edit_pubkey:
        edit_target = next((account for account in account_rows if account.pubkey == edit_pubkey), None)
    if delete_pubkey:
        delete_target = next((account for account in account_rows if account.pubkey == delete_pubkey), None)
    if delete_target:
        delete_target_trade_count = account_trade_counts.get(delete_target.id, 0)
        delete_target_ai_review_count = account_review_counts.get(delete_target.id, 0)
    total_trade_count = Trade.query.filter_by(user_id=user_id).count()
    total_ai_review_count = AIGeneratedResponse.query.filter_by(user_id=user_id).count()
    trade_account_status = request.args.get("trade_account_status", "").strip().lower()
    trade_account_message = request.args.get("trade_account_message", "").strip()
    if trade_account_status not in {"success", "error", "info"}:
        trade_account_status = ""
    if not trade_account_message:
        trade_account_status = ""

    return render_template(
        "trade_accounts.html",
        title="Trade Accounts | FX Journal",
        username=session.get("username", "User"),
        account_rows=account_rows,
        account_trade_counts=account_trade_counts,
        account_review_counts=account_review_counts,
        account_type_choices=get_account_type_choices(),
        edit_target=edit_target,
        delete_target=delete_target,
        delete_target_trade_count=delete_target_trade_count,
        delete_target_ai_review_count=delete_target_ai_review_count,
        total_trade_count=total_trade_count,
        total_ai_review_count=total_ai_review_count,
        active_trade_account=active_trade_account,
        trade_account_status=trade_account_status,
        trade_account_message=trade_account_message,
    )

@app.route("/dashboard/trades/new", methods=["GET", "POST"])
def new_trade():
    if not session.get("user_id"):
        return redirect(url_for("login"))
    user_id = session["user_id"]
    active_trade_account = get_active_trade_account_for_user(user_id)

    if request.method == "POST":
        input_timezone_name = get_display_timezone_name()
        account_type = normalize_account_type(active_trade_account.account_type)
        allowed_symbols = set(get_symbol_options(account_type))
        symbol = canonicalize_symbol(request.form.get("symbol", ""), account_type)
        contract_code = (request.form.get("contract_code", "") or "").strip().upper() or None
        if symbol not in allowed_symbols:
            return redirect(url_for("new_trade"))
        if account_type == "FUTURES" and contract_code:
            parsed_contract = parse_futures_contract_code(contract_code, expected_root=symbol)
            if parsed_contract is None:
                return redirect(url_for("new_trade"))
            contract_code = parsed_contract["contract_code"]
        elif account_type != "FUTURES":
            contract_code = None
        side = request.form.get("side", "BUY").strip().upper()
        status = request.form.get("status", "Running").strip().lower()
        entry_price = float(request.form.get("entry_price", 0.0))
        exit_price = request.form.get("exit_price", "").strip()
        exit_price = float(exit_price) if exit_price else None
        lot_size = float(request.form.get("lot_size", 0.01))
        trade_note = request.form.get("trade_note", "").strip()
        pnl = request.form.get("pnl", "").strip()
        pnl = float(pnl) if pnl else None
        opened_at = parse_local_datetime_input(request.form.get("opened_at", "").strip())
        if opened_at is None:
            opened_at = parse_local_datetime_input(request.form.get("trade_date", "").strip())
        if opened_at is None:
            opened_at = datetime.utcnow()
        closed_at = parse_local_datetime_input(request.form.get("closed_at", "").strip())
        if status != "closed":
            closed_at = None
        if closed_at is not None and closed_at < opened_at:
            closed_at = None

        if pnl is not None and exit_price is None:
            exit_price = derive_exit_price(
                symbol=symbol,
                side=side,
                entry_price=entry_price,
                lot_size=lot_size,
                pnl_value=pnl,
                instrument_type=account_type,
                contract_code=contract_code,
            )
        if pnl is None and exit_price is not None:
            pnl = calc_pnl_values(
                symbol=symbol,
                side=side,
                entry_price=entry_price,
                exit_price=exit_price,
                lot_size=lot_size,
                instrument_type=account_type,
                contract_code=contract_code,
            )
        trade = Trade(
            pubkey=build_unique_trade_pubkey(),
            user_id=user_id,
            trade_account_id=active_trade_account.id,
            source_timezone=input_timezone_name,
            symbol=symbol,
            contract_code=contract_code,
            side=side,
            entry_price=entry_price,
            lot_size=lot_size,
            trade_note=trade_note,
            pnl=pnl,
            exit_price=exit_price,
            opened_at=opened_at,
            closed_at=closed_at,
        )
        db.session.add(trade)
        db.session.commit()
        return redirect(url_for("trades"))

    import_status = request.args.get("import_status", "").strip().lower()
    import_message = request.args.get("import_message", "").strip()
    if import_status not in {"success", "error", "info"}:
        import_status = ""
    if not import_message:
        import_status = ""

    return render_template(
        "trade_entry.html",
        title="New Trade | FX Journal",
        username=session.get("username", "User"),
        symbol_options=get_symbol_options(active_trade_account.account_type),
        account_type=normalize_account_type(active_trade_account.account_type),
        size_label=get_trade_size_label(active_trade_account.account_type),
        import_status=import_status,
        import_message=import_message,
        trade=None,
        form_action=url_for("new_trade"),
        form_mode="new",
        opened_at_value="",
        closed_at_value="",
        analytics_timezone=get_display_timezone_name(),
    )


@app.route("/dashboard/import", methods=["POST"])
def import_trade_file():
    if not session.get("user_id"):
        return redirect(url_for("login"))
    user_id = session["user_id"]
    active_trade_account = get_active_trade_account_for_user(user_id)
    account_type = normalize_account_type(active_trade_account.account_type)
    import_stage = "request_validation"
    detected_profile = None
    parser_name = None
    total_rows = 0
    skipped_rows = 0
    parsed_rows = []
    validation_skipped = 0
    duplicate_count = 0
    import_signature = None
    current_row_index = None
    current_row_context = None

    uploaded_file = request.files.get("mt5_file")
    if not uploaded_file or not uploaded_file.filename:
        return redirect(
            url_for(
                "new_trade",
                import_status="error",
                import_message=(
                    "Please choose a Tradovate .csv file to upload."
                    if account_type == "FUTURES"
                    else "Please choose an MT5 .xlsx file to upload."
                ),
            )
        )

    try:
        import_stage = "detect_profile"
        uploaded_file.stream.seek(0)
        detected_profile = detect_trade_import_profile(uploaded_file.stream)
        if detected_profile is None:
            return redirect(
                url_for(
                    "new_trade",
                    import_status="error",
                    import_message="Unsupported or unrecognized import file. Use an MT5 Positions workbook or Tradovate Performance CSV.",
                )
            )

        detected_account_type = normalize_account_type(detected_profile.get("account_type"))
        if detected_account_type != account_type:
            return redirect(
                url_for(
                    "new_trade",
                    import_status="error",
                    import_message=(
                        f"Detected {detected_profile.get('platform', 'unknown')} "
                        f"{detected_profile.get('market_type', 'import')} file, "
                        f"but the active account is {account_type.title()}."
                    ),
                )
            )

        uploaded_file.stream.seek(0)
        parser_name = detected_profile.get("parser")
        import_stage = f"parse_{parser_name or 'unknown'}"
        if parser_name == "tradovate_csv":
            parsed_rows, total_rows, skipped_rows = parse_tradovate_csv_stream(uploaded_file.stream)
        else:
            parsed_rows, total_rows, skipped_rows = parse_mt5_xlsx_stream(uploaded_file.stream)
        if not parsed_rows:
            return redirect(
                url_for(
                    "new_trade",
                    import_status="error",
                    import_message=(
                        "No valid trade rows found in this Tradovate CSV."
                        if account_type == "FUTURES"
                        else "No valid trade rows found in this MT5 file."
                    ),
                )
            )

        allowed_symbols = set(get_symbol_options(active_trade_account.account_type))
        failed_symbols = set()
        validation_reasons = {
            "missing_mt5_position": 0,
            "invalid_mt5_position": 0,
            "invalid_side": 0,
            "invalid_entry_or_lot": 0,
            "invalid_exit_price": 0,
            "missing_open_time": 0,
        }

        existing_positions = set()
        import_positions = set()
        existing_trade_keys = set()
        import_trade_keys = set()
        if account_type == "FUTURES":
            existing_trades = (
                Trade.query.filter_by(
                    user_id=user_id,
                    trade_account_id=active_trade_account.id,
                )
                .all()
            )
            existing_trade_keys = {
                build_trade_duplicate_key(
                    symbol=trade.symbol,
                    contract_code=trade.contract_code,
                    side=trade.side,
                    entry_price=trade.entry_price,
                    exit_price=trade.exit_price,
                    lot_size=trade.lot_size,
                    opened_at=trade.opened_at,
                    closed_at=trade.closed_at,
                    pnl=resolve_pnl(trade),
                )
                for trade in existing_trades
            }
        else:
            existing_positions = {
                pos
                for (pos,) in db.session.query(Trade.mt5_position)
                .filter_by(
                    user_id=user_id,
                    trade_account_id=active_trade_account.id,
                )
                .filter(Trade.mt5_position.isnot(None))
                .all()
                if pos
            }

        import_stage = "build_insert_batch"
        import_signature = build_import_signature("tradovate" if account_type == "FUTURES" else "mt5")
        insert_batch = []
        reserved_pubkeys = set()

        for current_row_index, row in enumerate(parsed_rows, start=1):
            symbol = canonicalize_symbol(row.get("symbol"), active_trade_account.account_type)
            side = (row.get("side") or "").upper()
            lot_size = row.get("lot_size")
            entry_price = row.get("entry_price")
            exit_price = row.get("exit_price")
            pnl = row.get("pnl")
            opened_at = row.get("opened_at")
            closed_at = row.get("closed_at")
            contract_code = row.get("contract_code")
            mt5_position = row.get("mt5_position")
            mt5_position_raw = row.get("mt5_position_raw")
            current_row_context = {
                "symbol": symbol,
                "side": side,
                "lot_size": lot_size,
                "entry_price": entry_price,
                "exit_price": exit_price,
                "pnl": pnl,
                "opened_at": opened_at.isoformat() if opened_at else None,
                "closed_at": closed_at.isoformat() if closed_at else None,
                "contract_code": contract_code,
                "mt5_position": mt5_position,
                "mt5_position_raw": str(mt5_position_raw or "").strip()[:64] or None,
                "source_timezone": row.get("source_timezone"),
            }

            if symbol not in allowed_symbols:
                if symbol:
                    failed_symbols.add(symbol)
                validation_skipped += 1
                continue

            if account_type == "CFD":
                if mt5_position is None:
                    validation_skipped += 1
                    raw_text = str(mt5_position_raw or "").strip()
                    if raw_text:
                        validation_reasons["invalid_mt5_position"] += 1
                    else:
                        validation_reasons["missing_mt5_position"] += 1
                    continue

            if side not in {"BUY", "SELL"}:
                validation_skipped += 1
                validation_reasons["invalid_side"] += 1
                continue

            if lot_size is None or lot_size <= 0 or entry_price is None or entry_price <= 0:
                validation_skipped += 1
                validation_reasons["invalid_entry_or_lot"] += 1
                continue

            if exit_price is not None and exit_price <= 0:
                validation_skipped += 1
                validation_reasons["invalid_exit_price"] += 1
                continue

            if opened_at is None:
                validation_skipped += 1
                validation_reasons["missing_open_time"] += 1
                continue

            if pnl is None and exit_price is not None:
                pnl = calc_pnl_values(
                    symbol,
                    side,
                    entry_price,
                    exit_price,
                    lot_size,
                    instrument_type=active_trade_account.account_type,
                    contract_code=contract_code,
                )

            if account_type == "FUTURES":
                trade_key = build_trade_duplicate_key(
                    symbol=symbol,
                    contract_code=contract_code,
                    side=side,
                    entry_price=entry_price,
                    exit_price=exit_price,
                    lot_size=lot_size,
                    opened_at=opened_at,
                    closed_at=closed_at,
                    pnl=pnl,
                )
                if trade_key in existing_trade_keys or trade_key in import_trade_keys:
                    duplicate_count += 1
                    continue
                import_trade_keys.add(trade_key)
            else:
                if mt5_position in existing_positions or mt5_position in import_positions:
                    duplicate_count += 1
                    continue
                import_positions.add(mt5_position)

            insert_batch.append(
                Trade(
                    pubkey=build_unique_trade_pubkey(reserved_pubkeys),
                    user_id=user_id,
                    trade_account_id=active_trade_account.id,
                    source_timezone=(row.get("source_timezone") or None),
                    symbol=symbol,
                    mt5_position=mt5_position,
                    import_signature=import_signature,
                    contract_code=contract_code,
                    side=side,
                    entry_price=float(entry_price),
                    exit_price=float(exit_price) if exit_price is not None else None,
                    lot_size=float(lot_size),
                    pnl=float(pnl) if pnl is not None else None,
                    opened_at=opened_at,
                    closed_at=closed_at,
                    trade_note=(
                        "Imported from Tradovate Performance CSV"
                        if account_type == "FUTURES"
                        else "Imported from MT5 Positions"
                    ),
                )
            )

        if not insert_batch:
            symbol_msg = ""
            if failed_symbols:
                failed_list = sorted(failed_symbols)
                shown = ", ".join(failed_list[:8])
                extra = len(failed_list) - 8
                if extra > 0:
                    shown = f"{shown}, +{extra} more"
                symbol_msg = f" Unrecognized symbols: {shown}."
            return redirect(
                url_for(
                    "new_trade",
                    import_status="error",
                    import_message=(
                        f"No trades imported. Parsed {len(parsed_rows)} rows, "
                        f"skipped {skipped_rows + validation_skipped + duplicate_count}."
                        f"{symbol_msg}"
                    ),
                )
            )

        import_stage = "commit_import"
        db.session.add_all(insert_batch)
        db.session.commit()

        status = "success"
        if failed_symbols:
            status = "error"
        elif skipped_rows or validation_skipped or duplicate_count:
            status = "info"

        symbol_msg = ""
        if failed_symbols:
            failed_list = sorted(failed_symbols)
            shown = ", ".join(failed_list[:8])
            extra = len(failed_list) - 8
            if extra > 0:
                shown = f"{shown}, +{extra} more"
            symbol_msg = f" Unrecognized symbols skipped: {shown}."

        uncertain_bits = []
        if validation_reasons["missing_mt5_position"]:
            uncertain_bits.append(
                f"missing MT5 position {validation_reasons['missing_mt5_position']}"
            )
        if validation_reasons["invalid_mt5_position"]:
            uncertain_bits.append(
                f"invalid MT5 position {validation_reasons['invalid_mt5_position']}"
            )
        if validation_reasons["invalid_side"]:
            uncertain_bits.append(f"invalid side {validation_reasons['invalid_side']}")
        if validation_reasons["invalid_entry_or_lot"]:
            uncertain_bits.append(f"invalid entry/lot {validation_reasons['invalid_entry_or_lot']}")
        if validation_reasons["invalid_exit_price"]:
            uncertain_bits.append(f"invalid exit price {validation_reasons['invalid_exit_price']}")
        if validation_reasons["missing_open_time"]:
            uncertain_bits.append(f"missing open time {validation_reasons['missing_open_time']}")
        uncertain_msg = ""
        if uncertain_bits:
            uncertain_msg = " Data uncertainty checks: " + ", ".join(uncertain_bits) + "."

        return redirect(
            url_for(
                "new_trade",
                import_status=status,
                import_message=(
                    f"Imported {len(insert_batch)} trades from "
                    f"{'Tradovate CSV' if account_type == 'FUTURES' else 'Positions'}. "
                    f"Parsed rows: {len(parsed_rows)}/{total_rows}. "
                    f"Skipped: {skipped_rows + validation_skipped}. "
                    f"{'Duplicate trades' if account_type == 'FUTURES' else 'Duplicate positions'}: {duplicate_count}."
                    f" Import signature: {import_signature}."
                    f"{symbol_msg}"
                    f"{uncertain_msg}"
                ),
            )
        )
    except Exception as exc:
        db.session.rollback()
        app.logger.exception(
            "Trade import failed. stage=%s user_id=%s trade_account_id=%s account_type=%s "
            "filename=%r parser=%r detected_profile=%r parsed_rows=%s total_rows=%s skipped_rows=%s "
            "validation_skipped=%s duplicate_count=%s import_signature=%r current_row_index=%r "
            "current_row_context=%r",
            import_stage,
            user_id,
            getattr(active_trade_account, "id", None),
            account_type,
            getattr(uploaded_file, "filename", None),
            parser_name,
            detected_profile,
            len(parsed_rows) if parsed_rows is not None else None,
            total_rows,
            skipped_rows,
            validation_skipped,
            duplicate_count,
            import_signature,
            current_row_index,
            current_row_context,
            exc_info=exc,
        )
        extra_detail = ""
        if is_local_dev_environment():
            extra_detail = f" Details: {str(exc).strip()[:240]}"
        return redirect(
            url_for(
                "new_trade",
                import_status="error",
                import_message=(
                    "Upload processing failed. Check Tradovate CSV format and try again."
                    if account_type == "FUTURES"
                    else "Upload processing failed. Check MT5 export format and try again."
                ) + extra_detail,
            )
        )


@app.route("/dashboard/trades/<string:trade_pubkey>")
def trade_detail(trade_pubkey):
    if not session.get("user_id"):
        return redirect(url_for("login"))
    user_id = session["user_id"]

    trade = get_user_trade_by_pubkey_or_404(user_id, trade_pubkey)
    trade_pnl = resolve_pnl(trade)
    trade_pips = resolve_pips(trade)
    trade_ticks = resolve_ticks(trade)
    trade_account_type = get_trade_account_type(trade)
    timezone_name = get_display_timezone_name()
    opened_at_local = to_display_timezone(trade.opened_at, timezone_name)
    closed_at_local = to_display_timezone(trade.closed_at, timezone_name)

    return render_template(
        "trade_detail.html",
        title="Trade Detail | FX Journal",
        username=session.get("username", "User"),
        trade=trade,
        trade_display_symbol=format_trade_symbol(trade),
        trade_pnl=trade_pnl,
        trade_pips=trade_pips,
        trade_ticks=trade_ticks,
        trade_account_type=trade_account_type,
        trade_size_label=get_trade_size_label(trade_account_type),
        trade_opened_at_label=opened_at_local.strftime("%d %b %Y %H:%M") if opened_at_local else "-",
        trade_closed_at_label=closed_at_local.strftime("%d %b %Y %H:%M") if closed_at_local else "-",
        trade_source_timezone=trade.source_timezone or "Unknown",
        analytics_timezone=timezone_name,
    )


@app.route("/dashboard/trades/<string:trade_pubkey>/edit", methods=["GET", "POST"])
def edit_trade(trade_pubkey):
    if not session.get("user_id"):
        return redirect(url_for("login"))
    user_id = session["user_id"]

    trade = get_user_trade_by_pubkey_or_404(user_id, trade_pubkey)
    trade_account = trade.trade_account or get_active_trade_account_for_user(user_id)

    if request.method == "POST":
        input_timezone_name = get_display_timezone_name()
        account_type = normalize_account_type(trade_account.account_type)
        allowed_symbols = set(get_symbol_options(account_type, trade.symbol))
        symbol = canonicalize_symbol(request.form.get("symbol", ""), account_type)
        contract_code = (request.form.get("contract_code", "") or "").strip().upper() or None
        if symbol not in allowed_symbols:
            return redirect(url_for("edit_trade", trade_pubkey=trade.pubkey))
        if account_type == "FUTURES" and contract_code:
            parsed_contract = parse_futures_contract_code(contract_code, expected_root=symbol)
            if parsed_contract is None:
                return redirect(url_for("edit_trade", trade_pubkey=trade.pubkey))
            contract_code = parsed_contract["contract_code"]
        elif account_type != "FUTURES":
            contract_code = None
        side = request.form.get("side", "BUY").strip().upper()
        status = request.form.get("status", "Running").strip().lower()
        entry_price = float(request.form.get("entry_price", 0.0))
        exit_price = request.form.get("exit_price", "").strip()
        exit_price = float(exit_price) if exit_price else None
        lot_size = float(request.form.get("lot_size", 0.01))
        trade_note = request.form.get("trade_note", "").strip()
        pnl = request.form.get("pnl", "").strip()
        pnl = float(pnl) if pnl else None
        opened_at = parse_local_datetime_input(request.form.get("opened_at", "").strip())
        if opened_at is None:
            opened_at = parse_local_datetime_input(request.form.get("trade_date", "").strip())
        if opened_at is None:
            opened_at = trade.opened_at
        closed_at = parse_local_datetime_input(request.form.get("closed_at", "").strip())
        if status != "closed":
            closed_at = None
        elif closed_at is None:
            closed_at = trade.closed_at
        if closed_at is not None and opened_at is not None and closed_at < opened_at:
            closed_at = None

        if pnl is not None and exit_price is None:
            exit_price = derive_exit_price(
                symbol=symbol,
                side=side,
                entry_price=entry_price,
                lot_size=lot_size,
                pnl_value=pnl,
                instrument_type=account_type,
                contract_code=contract_code,
            )
        if pnl is None and exit_price is not None:
            pnl = calc_pnl_values(
                symbol=symbol,
                side=side,
                entry_price=entry_price,
                exit_price=exit_price,
                lot_size=lot_size,
                instrument_type=account_type,
                contract_code=contract_code,
            )

        trade.symbol = symbol
        trade.contract_code = contract_code
        trade.side = side
        trade.entry_price = entry_price
        trade.exit_price = exit_price
        trade.lot_size = lot_size
        trade.trade_note = trade_note
        trade.pnl = pnl
        trade.opened_at = opened_at
        trade.closed_at = closed_at
        trade.source_timezone = input_timezone_name

        db.session.commit()
        return redirect(url_for("trades"))

    return render_template(
        "trade_entry.html",
        title="Edit Trade | FX Journal",
        username=session.get("username", "User"),
        symbol_options=get_symbol_options(trade_account.account_type, trade.symbol),
        account_type=normalize_account_type(trade_account.account_type),
        size_label=get_trade_size_label(trade_account.account_type),
        trade=trade,
        form_action=url_for("edit_trade", trade_pubkey=trade.pubkey),
        form_mode="edit",
        opened_at_value=format_local_datetime_input(trade.opened_at),
        closed_at_value=format_local_datetime_input(trade.closed_at),
        analytics_timezone=get_display_timezone_name(),
    )


@app.route("/dashboard/trades/<string:trade_pubkey>/delete", methods=["POST"])
def delete_trade(trade_pubkey):
    if not session.get("user_id"):
        return redirect(url_for("login"))
    user_id = session["user_id"]

    trade = get_user_trade_by_pubkey_or_404(user_id, trade_pubkey)
    db.session.delete(trade)
    db.session.commit()
    return redirect(url_for("trades"))


@app.route("/dashboard/imports/delete", methods=["POST"])
def delete_import_batch():
    if not session.get("user_id"):
        return redirect(url_for("login"))
    user_id = session["user_id"]
    active_trade_account = get_active_trade_account_for_user(user_id)

    import_signature = request.form.get("import_signature", "").strip()
    if not import_signature:
        return redirect(
            url_for(
                "trades",
                manage="1",
                batch_delete_status="error",
                batch_delete_message="Please select an import batch to delete.",
            )
        )

    try:
        deleted = (
            Trade.query.filter_by(
                user_id=user_id,
                trade_account_id=active_trade_account.id,
                import_signature=import_signature,
            ).delete(synchronize_session=False)
        )
        db.session.commit()
    except (OperationalError, IntegrityError):
        db.session.rollback()
        return redirect(
            url_for(
                "trades",
                manage="1",
                batch_delete_status="error",
                batch_delete_message="Could not delete the selected import batch right now. Please try again.",
            )
        )

    status = "success" if deleted > 0 else "info"
    message = (
        f"Deleted {deleted} imported trade{'s' if deleted != 1 else ''} from the selected batch."
        if deleted > 0
        else f"No trades found for the selected import batch."
    )
    return redirect(
        url_for(
            "trades",
            manage="1",
            batch_delete_status=status,
            batch_delete_message=message,
        )
    )

if __name__ == "__main__":
    debug_mode = os.getenv("FLASK_DEBUG", "0").strip().lower() in {"1", "true", "yes"}
    app.run(debug=debug_mode)




